name: holiday_planner
description: Mobile app to plan and organize holiday trips
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.81.0
  meta: ^1.8.0
  uuid: ^3.0.7
  image_picker: ^1.0.4
  intl: ^0.18.0
  freezed_annotation: ^2.4.0
  palette_generator: ^0.3.0
  flutter_native_splash: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ">=8.0.0 <9.0.0"
  build_runner: ^2.4.6
  freezed: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_native_splash:
  web: false
  color: "#009688"
  image: assets/icon-512.png
  android_12:
    image: assets/adaptive-icon-512.png
    color: "#009688"

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#009688"
  adaptive_icon_foreground: "assets/adaptive-icon-512.png"
  ios: true
  image_path: "assets/icon-512.png"
  min_sdk_android: 21

