name: holiday_planner
description: "A mobile app helping you organize your holidays"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rust_lib_holiday_planner:
    path: rust_builder
  meta: ^1.8.0
  uuid: ^4.5.0
  image_picker: ^1.0.4
  file_selector: ^1.0.3
  intl: ^0.18.0
  freezed_annotation: ^2.4.0
  palette_generator: ^0.3.0
  flutter_native_splash: ^2.3.0
  flutter_rust_bridge: 2.11.1
  timelines_plus: ^1.0.3
  icons_plus: ^5.0.0
  material_design_icons_flutter: 7.0.7296
  open_app_file: ^4.0.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.2
  date_field: ^6.0.3+1
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_native_splash:
  web: false
  color: "#009688"
  image: assets/icon-512.png
  android_12:
    image: assets/adaptive-icon-512.png
    color: "#009688"

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#009688"
  adaptive_icon_foreground: "assets/adaptive-icon-512.png"
  ios: true
  image_path: "assets/icon-512.png"
  min_sdk_android: 21
