// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PointOfInterestOsmModel {
  final BigInt id;
  final String? openingHours;
  final String? website;
  final String? phoneNumber;

  const PointOfInterestOsmModel({
    required this.id,
    this.openingHours,
    this.website,
    this.phoneNumber,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      openingHours.hashCode ^
      website.hashCode ^
      phoneNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PointOfInterestOsmModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          openingHours == other.openingHours &&
          website == other.website &&
          phoneNumber == other.phoneNumber;
}

class PointOfInterestSearchModel {
  final BigInt id;
  final String name;
  final String? address;
  final String country;
  final Coordinate? coordinate;

  const PointOfInterestSearchModel({
    required this.id,
    required this.name,
    this.address,
    required this.country,
    this.coordinate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      address.hashCode ^
      country.hashCode ^
      coordinate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PointOfInterestSearchModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          address == other.address &&
          country == other.country &&
          coordinate == other.coordinate;
}
