// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class RouteModel {
  final UuidValue id;
  final UuidValue tripId;
  final RouteProvider provider;
  final String providerRouteId;
  final String name;
  final String? sport;
  final double distanceMeters;
  final PlatformInt64 durationSeconds;
  final double? elevationUpMeters;
  final double? elevationDownMeters;
  final Coordinate startCoordinate;
  final List<RoutePoint> polyline;
  final String? note;
  final String externalUrl;

  const RouteModel({
    required this.id,
    required this.tripId,
    required this.provider,
    required this.providerRouteId,
    required this.name,
    this.sport,
    required this.distanceMeters,
    required this.durationSeconds,
    this.elevationUpMeters,
    this.elevationDownMeters,
    required this.startCoordinate,
    required this.polyline,
    this.note,
    required this.externalUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tripId.hashCode ^
      provider.hashCode ^
      providerRouteId.hashCode ^
      name.hashCode ^
      sport.hashCode ^
      distanceMeters.hashCode ^
      durationSeconds.hashCode ^
      elevationUpMeters.hashCode ^
      elevationDownMeters.hashCode ^
      startCoordinate.hashCode ^
      polyline.hashCode ^
      note.hashCode ^
      externalUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tripId == other.tripId &&
          provider == other.provider &&
          providerRouteId == other.providerRouteId &&
          name == other.name &&
          sport == other.sport &&
          distanceMeters == other.distanceMeters &&
          durationSeconds == other.durationSeconds &&
          elevationUpMeters == other.elevationUpMeters &&
          elevationDownMeters == other.elevationDownMeters &&
          startCoordinate == other.startCoordinate &&
          polyline == other.polyline &&
          note == other.note &&
          externalUrl == other.externalUrl;
}

class RoutePoint {
  final Coordinate coordinate;
  final double? altitude;

  const RoutePoint({
    required this.coordinate,
    this.altitude,
  });

  @override
  int get hashCode => coordinate.hashCode ^ altitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutePoint &&
          runtimeType == other.runtimeType &&
          coordinate == other.coordinate &&
          altitude == other.altitude;
}

enum RouteProvider {
  komoot,
  ;
}
