// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TidalInformation {
  final DateTime date;
  final double height;
  final TideType tide;

  const TidalInformation({
    required this.date,
    required this.height,
    required this.tide,
  });

  @override
  int get hashCode => date.hashCode ^ height.hashCode ^ tide.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TidalInformation &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          height == other.height &&
          tide == other.tide;
}

enum TideType {
  high,
  low,
  ;
}
