// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'timeline.freezed.dart';

class TimelineItem {
  final DateTime date;
  final TimelineItemDetails details;

  const TimelineItem({
    required this.date,
    required this.details,
  });

  @override
  int get hashCode => date.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineItem &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          details == other.details;
}

@freezed
sealed class TimelineItemDetails with _$TimelineItemDetails {
  const TimelineItemDetails._();

  const factory TimelineItemDetails.carRentalPickUp({
    required String provider,
    required String address,
  }) = TimelineItemDetails_CarRentalPickUp;
  const factory TimelineItemDetails.carRentalDropOff({
    required String provider,
    required String address,
  }) = TimelineItemDetails_CarRentalDropOff;
  const factory TimelineItemDetails.reservation({
    required String title,
    String? address,
  }) = TimelineItemDetails_Reservation;
  const factory TimelineItemDetails.checkIn({
    String? address,
  }) = TimelineItemDetails_CheckIn;
  const factory TimelineItemDetails.checkOut({
    String? address,
  }) = TimelineItemDetails_CheckOut;
  const factory TimelineItemDetails.flightTakeOff({
    required String airport,
    required String flightNumber,
    String? seat,
  }) = TimelineItemDetails_FlightTakeOff;
  const factory TimelineItemDetails.flightLanding({
    required String airport,
    required String flightNumber,
  }) = TimelineItemDetails_FlightLanding;
  const factory TimelineItemDetails.trainOrigin({
    required String station,
    required String trainNumber,
    String? seat,
  }) = TimelineItemDetails_TrainOrigin;
  const factory TimelineItemDetails.trainDestination({
    required String station,
    required String trainNumber,
  }) = TimelineItemDetails_TrainDestination;
}

class TimelineModel {
  final List<TimelineItem> past;
  final List<TimelineItem> future;

  const TimelineModel({
    required this.past,
    required this.future,
  });

  @override
  int get hashCode => past.hashCode ^ future.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineModel &&
          runtimeType == other.runtimeType &&
          past == other.past &&
          future == other.future;
}
