// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ParsedTrainJourney {
  final List<ParsedTrainSegment> segments;
  final String? journeyUrl;

  const ParsedTrainJourney({
    required this.segments,
    this.journeyUrl,
  });

  @override
  int get hashCode => segments.hashCode ^ journeyUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedTrainJourney &&
          runtimeType == other.runtimeType &&
          segments == other.segments &&
          journeyUrl == other.journeyUrl;
}

class ParsedTrainSegment {
  final String? trainNumber;
  final String departureStationName;
  final String? departureStationCity;
  final String? departureStationCountry;
  final String? departureScheduledPlatform;
  final String arrivalStationName;
  final String? arrivalStationCity;
  final String? arrivalStationCountry;
  final String? arrivalScheduledPlatform;
  final DateTime scheduledDepartureTime;
  final DateTime scheduledArrivalTime;

  const ParsedTrainSegment({
    this.trainNumber,
    required this.departureStationName,
    this.departureStationCity,
    this.departureStationCountry,
    this.departureScheduledPlatform,
    required this.arrivalStationName,
    this.arrivalStationCity,
    this.arrivalStationCountry,
    this.arrivalScheduledPlatform,
    required this.scheduledDepartureTime,
    required this.scheduledArrivalTime,
  });

  @override
  int get hashCode =>
      trainNumber.hashCode ^
      departureStationName.hashCode ^
      departureStationCity.hashCode ^
      departureStationCountry.hashCode ^
      departureScheduledPlatform.hashCode ^
      arrivalStationName.hashCode ^
      arrivalStationCity.hashCode ^
      arrivalStationCountry.hashCode ^
      arrivalScheduledPlatform.hashCode ^
      scheduledDepartureTime.hashCode ^
      scheduledArrivalTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedTrainSegment &&
          runtimeType == other.runtimeType &&
          trainNumber == other.trainNumber &&
          departureStationName == other.departureStationName &&
          departureStationCity == other.departureStationCity &&
          departureStationCountry == other.departureStationCountry &&
          departureScheduledPlatform == other.departureScheduledPlatform &&
          arrivalStationName == other.arrivalStationName &&
          arrivalStationCity == other.arrivalStationCity &&
          arrivalStationCountry == other.arrivalStationCountry &&
          arrivalScheduledPlatform == other.arrivalScheduledPlatform &&
          scheduledDepartureTime == other.scheduledDepartureTime &&
          scheduledArrivalTime == other.scheduledArrivalTime;
}

class Train {
  final String? trainNumber;
  final TrainStation departure;
  final TrainStation arrival;
  final DateTime scheduledDepartureTime;
  final DateTime scheduledArrivalTime;
  final DateTime? estimatedDepartureTime;
  final DateTime? estimatedArrivalTime;

  const Train({
    this.trainNumber,
    required this.departure,
    required this.arrival,
    required this.scheduledDepartureTime,
    required this.scheduledArrivalTime,
    this.estimatedDepartureTime,
    this.estimatedArrivalTime,
  });

  @override
  int get hashCode =>
      trainNumber.hashCode ^
      departure.hashCode ^
      arrival.hashCode ^
      scheduledDepartureTime.hashCode ^
      scheduledArrivalTime.hashCode ^
      estimatedDepartureTime.hashCode ^
      estimatedArrivalTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Train &&
          runtimeType == other.runtimeType &&
          trainNumber == other.trainNumber &&
          departure == other.departure &&
          arrival == other.arrival &&
          scheduledDepartureTime == other.scheduledDepartureTime &&
          scheduledArrivalTime == other.scheduledArrivalTime &&
          estimatedDepartureTime == other.estimatedDepartureTime &&
          estimatedArrivalTime == other.estimatedArrivalTime;
}

class TrainStation {
  final String name;
  final String scheduledPlatform;
  final String? actualPlatform;
  final String? city;
  final String? country;

  const TrainStation({
    required this.name,
    required this.scheduledPlatform,
    this.actualPlatform,
    this.city,
    this.country,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      scheduledPlatform.hashCode ^
      actualPlatform.hashCode ^
      city.hashCode ^
      country.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrainStation &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          scheduledPlatform == other.scheduledPlatform &&
          actualPlatform == other.actualPlatform &&
          city == other.city &&
          country == other.country;
}
