// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'bookings.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'trip_day.freezed.dart';

class DayItem {
  final DateTime? scheduledAt;
  final DayItemDetails details;

  const DayItem({
    this.scheduledAt,
    required this.details,
  });

  @override
  int get hashCode => scheduledAt.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DayItem &&
          runtimeType == other.runtimeType &&
          scheduledAt == other.scheduledAt &&
          details == other.details;
}

@freezed
sealed class DayItemDetails with _$DayItemDetails {
  const DayItemDetails._();

  const factory DayItemDetails.pointOfInterest({
    required UuidValue id,
    required String name,
    required String address,
    required int dayOrder,
  }) = DayItemDetails_PointOfInterest;
  const factory DayItemDetails.route({
    required UuidValue id,
    required String name,
    String? sport,
    required double distanceMeters,
    required PlatformInt64 durationSeconds,
    required int dayOrder,
  }) = DayItemDetails_Route;
  const factory DayItemDetails.accommodationCheckIn({
    required UuidValue accommodationId,
    required String name,
    String? address,
    required DateTime checkIn,
  }) = DayItemDetails_AccommodationCheckIn;
  const factory DayItemDetails.accommodationCheckOut({
    required UuidValue accommodationId,
    required String name,
    String? address,
    required DateTime checkOut,
  }) = DayItemDetails_AccommodationCheckOut;
  const factory DayItemDetails.accommodationStay({
    required UuidValue accommodationId,
    required String name,
  }) = DayItemDetails_AccommodationStay;
  const factory DayItemDetails.trainDeparture({
    required UuidValue trainId,
    required String station,
    String? trainNumber,
    String? seat,
    required DateTime scheduled,
  }) = DayItemDetails_TrainDeparture;
  const factory DayItemDetails.trainArrival({
    required UuidValue trainId,
    required String station,
    String? trainNumber,
    required DateTime scheduled,
  }) = DayItemDetails_TrainArrival;
  const factory DayItemDetails.reservation({
    required UuidValue reservationId,
    required String title,
    String? address,
    required ReservationCategory category,
    required DateTime start,
    DateTime? end,
  }) = DayItemDetails_Reservation;
  const factory DayItemDetails.carRentalPickUp({
    required UuidValue carRentalId,
    required String provider,
    required String address,
    required DateTime pickUp,
  }) = DayItemDetails_CarRentalPickUp;
  const factory DayItemDetails.carRentalDropOff({
    required UuidValue carRentalId,
    required String provider,
    String? address,
    required DateTime dropOff,
  }) = DayItemDetails_CarRentalDropOff;
}

class DayLocation {
  final UuidValue locationId;
  final String city;
  final String country;
  final Coordinate coordinates;
  final bool isPrimary;

  const DayLocation({
    required this.locationId,
    required this.city,
    required this.country,
    required this.coordinates,
    required this.isPrimary,
  });

  @override
  int get hashCode =>
      locationId.hashCode ^
      city.hashCode ^
      country.hashCode ^
      coordinates.hashCode ^
      isPrimary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DayLocation &&
          runtimeType == other.runtimeType &&
          locationId == other.locationId &&
          city == other.city &&
          country == other.country &&
          coordinates == other.coordinates &&
          isPrimary == other.isPrimary;
}

class DayWeather {
  final UuidValue locationId;
  final double minTemperature;
  final double maxTemperature;
  final WeatherCondition condition;
  final double precipitationAmount;
  final double precipitationProbability;

  const DayWeather({
    required this.locationId,
    required this.minTemperature,
    required this.maxTemperature,
    required this.condition,
    required this.precipitationAmount,
    required this.precipitationProbability,
  });

  @override
  int get hashCode =>
      locationId.hashCode ^
      minTemperature.hashCode ^
      maxTemperature.hashCode ^
      condition.hashCode ^
      precipitationAmount.hashCode ^
      precipitationProbability.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DayWeather &&
          runtimeType == other.runtimeType &&
          locationId == other.locationId &&
          minTemperature == other.minTemperature &&
          maxTemperature == other.maxTemperature &&
          condition == other.condition &&
          precipitationAmount == other.precipitationAmount &&
          precipitationProbability == other.precipitationProbability;
}

class TripDayView {
  final UuidValue? id;
  final UuidValue tripId;
  final DateTime date;
  final int dayIndex;
  final String? title;
  final List<DayLocation> locations;
  final DayWeather? weather;
  final List<DayItem> items;

  const TripDayView({
    this.id,
    required this.tripId,
    required this.date,
    required this.dayIndex,
    this.title,
    required this.locations,
    this.weather,
    required this.items,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tripId.hashCode ^
      date.hashCode ^
      dayIndex.hashCode ^
      title.hashCode ^
      locations.hashCode ^
      weather.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripDayView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tripId == other.tripId &&
          date == other.date &&
          dayIndex == other.dayIndex &&
          title == other.title &&
          locations == other.locations &&
          weather == other.weather &&
          items == other.items;
}

class UnassignedItems {
  final List<UnassignedPoi> pointsOfInterest;
  final List<UnassignedRoute> routes;

  const UnassignedItems({
    required this.pointsOfInterest,
    required this.routes,
  });

  @override
  int get hashCode => pointsOfInterest.hashCode ^ routes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnassignedItems &&
          runtimeType == other.runtimeType &&
          pointsOfInterest == other.pointsOfInterest &&
          routes == other.routes;
}

class UnassignedPoi {
  final UuidValue id;
  final String name;
  final String address;

  const UnassignedPoi({
    required this.id,
    required this.name,
    required this.address,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnassignedPoi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          address == other.address;
}

class UnassignedRoute {
  final UuidValue id;
  final String name;
  final String? sport;
  final double distanceMeters;
  final PlatformInt64 durationSeconds;

  const UnassignedRoute({
    required this.id,
    required this.name,
    this.sport,
    required this.distanceMeters,
    required this.durationSeconds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      sport.hashCode ^
      distanceMeters.hashCode ^
      durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnassignedRoute &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          sport == other.sport &&
          distanceMeters == other.distanceMeters &&
          durationSeconds == other.durationSeconds;
}
