// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class WebImage {
  final String id;
  final String url;
  final String thumbnailUrl;
  final String author;
  final String? description;

  const WebImage({
    required this.id,
    required this.url,
    required this.thumbnailUrl,
    required this.author,
    this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      url.hashCode ^
      thumbnailUrl.hashCode ^
      author.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebImage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          url == other.url &&
          thumbnailUrl == other.thumbnailUrl &&
          author == other.author &&
          description == other.description;
}
