// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/accommodations.dart';
import 'api/attachments.dart';
import 'api/packing_list.dart';
import 'api/points_of_interest.dart';
import 'api/trips.dart';
import 'commands/add_packing_list_entry.dart';
import 'commands/add_trip_accommodation.dart';
import 'commands/add_trip_attachment.dart';
import 'commands/add_trip_location.dart';
import 'commands/add_trip_point_of_interest.dart';
import 'commands/create_trip.dart';
import 'commands/delete_packing_list_entry.dart';
import 'commands/update_packing_list_entry.dart';
import 'commands/update_trip_accommodation.dart';
import 'commands/update_trip_point_of_interest.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  AccommodationModel dco_decode_accommodation_model(dynamic raw);

  @protected
  AddPackingListEntry dco_decode_add_packing_list_entry(dynamic raw);

  @protected
  AddTripAccommodation dco_decode_add_trip_accommodation(dynamic raw);

  @protected
  AddTripAttachment dco_decode_add_trip_attachment(dynamic raw);

  @protected
  AddTripLocation dco_decode_add_trip_location(dynamic raw);

  @protected
  AddTripPointOfInterest dco_decode_add_trip_point_of_interest(dynamic raw);

  @protected
  AttachmentListModel dco_decode_attachment_list_model(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  AddPackingListEntry dco_decode_box_autoadd_add_packing_list_entry(
      dynamic raw);

  @protected
  AddTripAccommodation dco_decode_box_autoadd_add_trip_accommodation(
      dynamic raw);

  @protected
  AddTripAttachment dco_decode_box_autoadd_add_trip_attachment(dynamic raw);

  @protected
  AddTripLocation dco_decode_box_autoadd_add_trip_location(dynamic raw);

  @protected
  AddTripPointOfInterest dco_decode_box_autoadd_add_trip_point_of_interest(
      dynamic raw);

  @protected
  CreateTrip dco_decode_box_autoadd_create_trip(dynamic raw);

  @protected
  DeletePackingListEntry dco_decode_box_autoadd_delete_packing_list_entry(
      dynamic raw);

  @protected
  UpdatePackingListEntry dco_decode_box_autoadd_update_packing_list_entry(
      dynamic raw);

  @protected
  UpdateTripAccommodation dco_decode_box_autoadd_update_trip_accommodation(
      dynamic raw);

  @protected
  UpdateTripPointOfInterest
      dco_decode_box_autoadd_update_trip_point_of_interest(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  WeatherForecast dco_decode_box_autoadd_weather_forecast(dynamic raw);

  @protected
  Coordinates dco_decode_coordinates(dynamic raw);

  @protected
  CreateTrip dco_decode_create_trip(dynamic raw);

  @protected
  DailyWeatherForecast dco_decode_daily_weather_forecast(dynamic raw);

  @protected
  DeletePackingListEntry dco_decode_delete_packing_list_entry(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HourlyWeatherForecast dco_decode_hourly_weather_forecast(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<AccommodationModel> dco_decode_list_accommodation_model(dynamic raw);

  @protected
  List<AttachmentListModel> dco_decode_list_attachment_list_model(dynamic raw);

  @protected
  List<DailyWeatherForecast> dco_decode_list_daily_weather_forecast(
      dynamic raw);

  @protected
  List<HourlyWeatherForecast> dco_decode_list_hourly_weather_forecast(
      dynamic raw);

  @protected
  List<LocationEntry> dco_decode_list_location_entry(dynamic raw);

  @protected
  List<PackingListEntry> dco_decode_list_packing_list_entry(dynamic raw);

  @protected
  List<PackingListEntryCondition> dco_decode_list_packing_list_entry_condition(
      dynamic raw);

  @protected
  List<PointOfInterestModel> dco_decode_list_point_of_interest_model(
      dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TripAttachment> dco_decode_list_trip_attachment(dynamic raw);

  @protected
  List<TripListModel> dco_decode_list_trip_list_model(dynamic raw);

  @protected
  List<TripLocationListModel> dco_decode_list_trip_location_list_model(
      dynamic raw);

  @protected
  List<TripPackingListEntry> dco_decode_list_trip_packing_list_entry(
      dynamic raw);

  @protected
  List<TripPackingListGroup> dco_decode_list_trip_packing_list_group(
      dynamic raw);

  @protected
  LocationEntry dco_decode_location_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  WeatherForecast? dco_decode_opt_box_autoadd_weather_forecast(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PackingListEntry dco_decode_packing_list_entry(dynamic raw);

  @protected
  PackingListEntryCondition dco_decode_packing_list_entry_condition(
      dynamic raw);

  @protected
  PointOfInterestModel dco_decode_point_of_interest_model(dynamic raw);

  @protected
  Quantity dco_decode_quantity(dynamic raw);

  @protected
  TripAttachment dco_decode_trip_attachment(dynamic raw);

  @protected
  TripListModel dco_decode_trip_list_model(dynamic raw);

  @protected
  TripLocationListModel dco_decode_trip_location_list_model(dynamic raw);

  @protected
  TripOverviewModel dco_decode_trip_overview_model(dynamic raw);

  @protected
  TripPackingListEntry dco_decode_trip_packing_list_entry(dynamic raw);

  @protected
  TripPackingListGroup dco_decode_trip_packing_list_group(dynamic raw);

  @protected
  TripPackingListModel dco_decode_trip_packing_list_model(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdatePackingListEntry dco_decode_update_packing_list_entry(dynamic raw);

  @protected
  UpdateTripAccommodation dco_decode_update_trip_accommodation(dynamic raw);

  @protected
  UpdateTripPointOfInterest dco_decode_update_trip_point_of_interest(
      dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WeatherCondition dco_decode_weather_condition(dynamic raw);

  @protected
  WeatherForecast dco_decode_weather_forecast(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  AccommodationModel sse_decode_accommodation_model(
      SseDeserializer deserializer);

  @protected
  AddPackingListEntry sse_decode_add_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  AddTripAccommodation sse_decode_add_trip_accommodation(
      SseDeserializer deserializer);

  @protected
  AddTripAttachment sse_decode_add_trip_attachment(
      SseDeserializer deserializer);

  @protected
  AddTripLocation sse_decode_add_trip_location(SseDeserializer deserializer);

  @protected
  AddTripPointOfInterest sse_decode_add_trip_point_of_interest(
      SseDeserializer deserializer);

  @protected
  AttachmentListModel sse_decode_attachment_list_model(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  AddPackingListEntry sse_decode_box_autoadd_add_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  AddTripAccommodation sse_decode_box_autoadd_add_trip_accommodation(
      SseDeserializer deserializer);

  @protected
  AddTripAttachment sse_decode_box_autoadd_add_trip_attachment(
      SseDeserializer deserializer);

  @protected
  AddTripLocation sse_decode_box_autoadd_add_trip_location(
      SseDeserializer deserializer);

  @protected
  AddTripPointOfInterest sse_decode_box_autoadd_add_trip_point_of_interest(
      SseDeserializer deserializer);

  @protected
  CreateTrip sse_decode_box_autoadd_create_trip(SseDeserializer deserializer);

  @protected
  DeletePackingListEntry sse_decode_box_autoadd_delete_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  UpdatePackingListEntry sse_decode_box_autoadd_update_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  UpdateTripAccommodation sse_decode_box_autoadd_update_trip_accommodation(
      SseDeserializer deserializer);

  @protected
  UpdateTripPointOfInterest
      sse_decode_box_autoadd_update_trip_point_of_interest(
          SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WeatherForecast sse_decode_box_autoadd_weather_forecast(
      SseDeserializer deserializer);

  @protected
  Coordinates sse_decode_coordinates(SseDeserializer deserializer);

  @protected
  CreateTrip sse_decode_create_trip(SseDeserializer deserializer);

  @protected
  DailyWeatherForecast sse_decode_daily_weather_forecast(
      SseDeserializer deserializer);

  @protected
  DeletePackingListEntry sse_decode_delete_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HourlyWeatherForecast sse_decode_hourly_weather_forecast(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<AccommodationModel> sse_decode_list_accommodation_model(
      SseDeserializer deserializer);

  @protected
  List<AttachmentListModel> sse_decode_list_attachment_list_model(
      SseDeserializer deserializer);

  @protected
  List<DailyWeatherForecast> sse_decode_list_daily_weather_forecast(
      SseDeserializer deserializer);

  @protected
  List<HourlyWeatherForecast> sse_decode_list_hourly_weather_forecast(
      SseDeserializer deserializer);

  @protected
  List<LocationEntry> sse_decode_list_location_entry(
      SseDeserializer deserializer);

  @protected
  List<PackingListEntry> sse_decode_list_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  List<PackingListEntryCondition> sse_decode_list_packing_list_entry_condition(
      SseDeserializer deserializer);

  @protected
  List<PointOfInterestModel> sse_decode_list_point_of_interest_model(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TripAttachment> sse_decode_list_trip_attachment(
      SseDeserializer deserializer);

  @protected
  List<TripListModel> sse_decode_list_trip_list_model(
      SseDeserializer deserializer);

  @protected
  List<TripLocationListModel> sse_decode_list_trip_location_list_model(
      SseDeserializer deserializer);

  @protected
  List<TripPackingListEntry> sse_decode_list_trip_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  List<TripPackingListGroup> sse_decode_list_trip_packing_list_group(
      SseDeserializer deserializer);

  @protected
  LocationEntry sse_decode_location_entry(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WeatherForecast? sse_decode_opt_box_autoadd_weather_forecast(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PackingListEntry sse_decode_packing_list_entry(SseDeserializer deserializer);

  @protected
  PackingListEntryCondition sse_decode_packing_list_entry_condition(
      SseDeserializer deserializer);

  @protected
  PointOfInterestModel sse_decode_point_of_interest_model(
      SseDeserializer deserializer);

  @protected
  Quantity sse_decode_quantity(SseDeserializer deserializer);

  @protected
  TripAttachment sse_decode_trip_attachment(SseDeserializer deserializer);

  @protected
  TripListModel sse_decode_trip_list_model(SseDeserializer deserializer);

  @protected
  TripLocationListModel sse_decode_trip_location_list_model(
      SseDeserializer deserializer);

  @protected
  TripOverviewModel sse_decode_trip_overview_model(
      SseDeserializer deserializer);

  @protected
  TripPackingListEntry sse_decode_trip_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  TripPackingListGroup sse_decode_trip_packing_list_group(
      SseDeserializer deserializer);

  @protected
  TripPackingListModel sse_decode_trip_packing_list_model(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdatePackingListEntry sse_decode_update_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  UpdateTripAccommodation sse_decode_update_trip_accommodation(
      SseDeserializer deserializer);

  @protected
  UpdateTripPointOfInterest sse_decode_update_trip_point_of_interest(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WeatherCondition sse_decode_weather_condition(SseDeserializer deserializer);

  @protected
  WeatherForecast sse_decode_weather_forecast(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_accommodation_model(
      AccommodationModel self, SseSerializer serializer);

  @protected
  void sse_encode_add_packing_list_entry(
      AddPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_accommodation(
      AddTripAccommodation self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_attachment(
      AddTripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_location(
      AddTripLocation self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_point_of_interest(
      AddTripPointOfInterest self, SseSerializer serializer);

  @protected
  void sse_encode_attachment_list_model(
      AttachmentListModel self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
      DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_packing_list_entry(
      AddPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_accommodation(
      AddTripAccommodation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_attachment(
      AddTripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_location(
      AddTripLocation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_point_of_interest(
      AddTripPointOfInterest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_trip(
      CreateTrip self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delete_packing_list_entry(
      DeletePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_packing_list_entry(
      UpdatePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_trip_accommodation(
      UpdateTripAccommodation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_trip_point_of_interest(
      UpdateTripPointOfInterest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_weather_forecast(
      WeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_coordinates(Coordinates self, SseSerializer serializer);

  @protected
  void sse_encode_create_trip(CreateTrip self, SseSerializer serializer);

  @protected
  void sse_encode_daily_weather_forecast(
      DailyWeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_delete_packing_list_entry(
      DeletePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_hourly_weather_forecast(
      HourlyWeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_accommodation_model(
      List<AccommodationModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_attachment_list_model(
      List<AttachmentListModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_daily_weather_forecast(
      List<DailyWeatherForecast> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hourly_weather_forecast(
      List<HourlyWeatherForecast> self, SseSerializer serializer);

  @protected
  void sse_encode_list_location_entry(
      List<LocationEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_packing_list_entry(
      List<PackingListEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_packing_list_entry_condition(
      List<PackingListEntryCondition> self, SseSerializer serializer);

  @protected
  void sse_encode_list_point_of_interest_model(
      List<PointOfInterestModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_attachment(
      List<TripAttachment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_list_model(
      List<TripListModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_location_list_model(
      List<TripLocationListModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_packing_list_entry(
      List<TripPackingListEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_packing_list_group(
      List<TripPackingListGroup> self, SseSerializer serializer);

  @protected
  void sse_encode_location_entry(LocationEntry self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
      DateTime? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_weather_forecast(
      WeatherForecast? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_packing_list_entry(
      PackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_packing_list_entry_condition(
      PackingListEntryCondition self, SseSerializer serializer);

  @protected
  void sse_encode_point_of_interest_model(
      PointOfInterestModel self, SseSerializer serializer);

  @protected
  void sse_encode_quantity(Quantity self, SseSerializer serializer);

  @protected
  void sse_encode_trip_attachment(
      TripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_trip_list_model(TripListModel self, SseSerializer serializer);

  @protected
  void sse_encode_trip_location_list_model(
      TripLocationListModel self, SseSerializer serializer);

  @protected
  void sse_encode_trip_overview_model(
      TripOverviewModel self, SseSerializer serializer);

  @protected
  void sse_encode_trip_packing_list_entry(
      TripPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_trip_packing_list_group(
      TripPackingListGroup self, SseSerializer serializer);

  @protected
  void sse_encode_trip_packing_list_model(
      TripPackingListModel self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_packing_list_entry(
      UpdatePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_update_trip_accommodation(
      UpdateTripAccommodation self, SseSerializer serializer);

  @protected
  void sse_encode_update_trip_point_of_interest(
      UpdateTripPointOfInterest self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_weather_condition(
      WeatherCondition self, SseSerializer serializer);

  @protected
  void sse_encode_weather_forecast(
      WeatherForecast self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
