// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/attachments.dart';
import 'api/packing_list.dart';
import 'api/trips.dart';
import 'commands/add_packing_list_entry.dart';
import 'commands/add_trip_attachment.dart';
import 'commands/add_trip_location.dart';
import 'commands/create_trip.dart';
import 'commands/delete_packing_list_entry.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'models.dart';
import 'models/transits.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  Accomodation dco_decode_accomodation(dynamic raw);

  @protected
  AddPackingListEntry dco_decode_add_packing_list_entry(dynamic raw);

  @protected
  AddTripAttachment dco_decode_add_trip_attachment(dynamic raw);

  @protected
  AddTripLocation dco_decode_add_trip_location(dynamic raw);

  @protected
  Airport dco_decode_airport(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  AddPackingListEntry dco_decode_box_autoadd_add_packing_list_entry(
      dynamic raw);

  @protected
  AddTripAttachment dco_decode_box_autoadd_add_trip_attachment(dynamic raw);

  @protected
  AddTripLocation dco_decode_box_autoadd_add_trip_location(dynamic raw);

  @protected
  CreateTrip dco_decode_box_autoadd_create_trip(dynamic raw);

  @protected
  DeletePackingListEntry dco_decode_box_autoadd_delete_packing_list_entry(
      dynamic raw);

  @protected
  Flight dco_decode_box_autoadd_flight(dynamic raw);

  @protected
  Train dco_decode_box_autoadd_train(dynamic raw);

  @protected
  Trip dco_decode_box_autoadd_trip(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  WeatherForecast dco_decode_box_autoadd_weather_forecast(dynamic raw);

  @protected
  Coordinates dco_decode_coordinates(dynamic raw);

  @protected
  CreateTrip dco_decode_create_trip(dynamic raw);

  @protected
  DailyWeatherForecast dco_decode_daily_weather_forecast(dynamic raw);

  @protected
  DeletePackingListEntry dco_decode_delete_packing_list_entry(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Flight dco_decode_flight(dynamic raw);

  @protected
  HourlyWeatherForecast dco_decode_hourly_weather_forecast(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Accomodation> dco_decode_list_accomodation(dynamic raw);

  @protected
  List<DailyWeatherForecast> dco_decode_list_daily_weather_forecast(
      dynamic raw);

  @protected
  List<HourlyWeatherForecast> dco_decode_list_hourly_weather_forecast(
      dynamic raw);

  @protected
  List<Location> dco_decode_list_location(dynamic raw);

  @protected
  List<LocationEntry> dco_decode_list_location_entry(dynamic raw);

  @protected
  List<PackingListEntry> dco_decode_list_packing_list_entry(dynamic raw);

  @protected
  List<PackingListEntryCondition> dco_decode_list_packing_list_entry_condition(
      dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Transit> dco_decode_list_transit(dynamic raw);

  @protected
  List<Trip> dco_decode_list_trip(dynamic raw);

  @protected
  List<TripAttachment> dco_decode_list_trip_attachment(dynamic raw);

  @protected
  List<TripPackingListEntry> dco_decode_list_trip_packing_list_entry(
      dynamic raw);

  @protected
  Location dco_decode_location(dynamic raw);

  @protected
  LocationEntry dco_decode_location_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  Trip? dco_decode_opt_box_autoadd_trip(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  WeatherForecast? dco_decode_opt_box_autoadd_weather_forecast(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PackingListEntry dco_decode_packing_list_entry(dynamic raw);

  @protected
  PackingListEntryCondition dco_decode_packing_list_entry_condition(
      dynamic raw);

  @protected
  Quantity dco_decode_quantity(dynamic raw);

  @protected
  Train dco_decode_train(dynamic raw);

  @protected
  TrainStation dco_decode_train_station(dynamic raw);

  @protected
  Transit dco_decode_transit(dynamic raw);

  @protected
  Trip dco_decode_trip(dynamic raw);

  @protected
  TripAttachment dco_decode_trip_attachment(dynamic raw);

  @protected
  TripPackingListEntry dco_decode_trip_packing_list_entry(dynamic raw);

  @protected
  TripPackingListModel dco_decode_trip_packing_list_model(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WeatherCondition dco_decode_weather_condition(dynamic raw);

  @protected
  WeatherForecast dco_decode_weather_forecast(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  Accomodation sse_decode_accomodation(SseDeserializer deserializer);

  @protected
  AddPackingListEntry sse_decode_add_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  AddTripAttachment sse_decode_add_trip_attachment(
      SseDeserializer deserializer);

  @protected
  AddTripLocation sse_decode_add_trip_location(SseDeserializer deserializer);

  @protected
  Airport sse_decode_airport(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  AddPackingListEntry sse_decode_box_autoadd_add_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  AddTripAttachment sse_decode_box_autoadd_add_trip_attachment(
      SseDeserializer deserializer);

  @protected
  AddTripLocation sse_decode_box_autoadd_add_trip_location(
      SseDeserializer deserializer);

  @protected
  CreateTrip sse_decode_box_autoadd_create_trip(SseDeserializer deserializer);

  @protected
  DeletePackingListEntry sse_decode_box_autoadd_delete_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  Flight sse_decode_box_autoadd_flight(SseDeserializer deserializer);

  @protected
  Train sse_decode_box_autoadd_train(SseDeserializer deserializer);

  @protected
  Trip sse_decode_box_autoadd_trip(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WeatherForecast sse_decode_box_autoadd_weather_forecast(
      SseDeserializer deserializer);

  @protected
  Coordinates sse_decode_coordinates(SseDeserializer deserializer);

  @protected
  CreateTrip sse_decode_create_trip(SseDeserializer deserializer);

  @protected
  DailyWeatherForecast sse_decode_daily_weather_forecast(
      SseDeserializer deserializer);

  @protected
  DeletePackingListEntry sse_decode_delete_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Flight sse_decode_flight(SseDeserializer deserializer);

  @protected
  HourlyWeatherForecast sse_decode_hourly_weather_forecast(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Accomodation> sse_decode_list_accomodation(SseDeserializer deserializer);

  @protected
  List<DailyWeatherForecast> sse_decode_list_daily_weather_forecast(
      SseDeserializer deserializer);

  @protected
  List<HourlyWeatherForecast> sse_decode_list_hourly_weather_forecast(
      SseDeserializer deserializer);

  @protected
  List<Location> sse_decode_list_location(SseDeserializer deserializer);

  @protected
  List<LocationEntry> sse_decode_list_location_entry(
      SseDeserializer deserializer);

  @protected
  List<PackingListEntry> sse_decode_list_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  List<PackingListEntryCondition> sse_decode_list_packing_list_entry_condition(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Transit> sse_decode_list_transit(SseDeserializer deserializer);

  @protected
  List<Trip> sse_decode_list_trip(SseDeserializer deserializer);

  @protected
  List<TripAttachment> sse_decode_list_trip_attachment(
      SseDeserializer deserializer);

  @protected
  List<TripPackingListEntry> sse_decode_list_trip_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  Location sse_decode_location(SseDeserializer deserializer);

  @protected
  LocationEntry sse_decode_location_entry(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Trip? sse_decode_opt_box_autoadd_trip(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WeatherForecast? sse_decode_opt_box_autoadd_weather_forecast(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PackingListEntry sse_decode_packing_list_entry(SseDeserializer deserializer);

  @protected
  PackingListEntryCondition sse_decode_packing_list_entry_condition(
      SseDeserializer deserializer);

  @protected
  Quantity sse_decode_quantity(SseDeserializer deserializer);

  @protected
  Train sse_decode_train(SseDeserializer deserializer);

  @protected
  TrainStation sse_decode_train_station(SseDeserializer deserializer);

  @protected
  Transit sse_decode_transit(SseDeserializer deserializer);

  @protected
  Trip sse_decode_trip(SseDeserializer deserializer);

  @protected
  TripAttachment sse_decode_trip_attachment(SseDeserializer deserializer);

  @protected
  TripPackingListEntry sse_decode_trip_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  TripPackingListModel sse_decode_trip_packing_list_model(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WeatherCondition sse_decode_weather_condition(SseDeserializer deserializer);

  @protected
  WeatherForecast sse_decode_weather_forecast(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_accomodation(Accomodation self, SseSerializer serializer);

  @protected
  void sse_encode_add_packing_list_entry(
      AddPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_attachment(
      AddTripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_location(
      AddTripLocation self, SseSerializer serializer);

  @protected
  void sse_encode_airport(Airport self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
      DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_packing_list_entry(
      AddPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_attachment(
      AddTripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_location(
      AddTripLocation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_trip(
      CreateTrip self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delete_packing_list_entry(
      DeletePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flight(Flight self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_train(Train self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_trip(Trip self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_weather_forecast(
      WeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_coordinates(Coordinates self, SseSerializer serializer);

  @protected
  void sse_encode_create_trip(CreateTrip self, SseSerializer serializer);

  @protected
  void sse_encode_daily_weather_forecast(
      DailyWeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_delete_packing_list_entry(
      DeletePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_flight(Flight self, SseSerializer serializer);

  @protected
  void sse_encode_hourly_weather_forecast(
      HourlyWeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_accomodation(
      List<Accomodation> self, SseSerializer serializer);

  @protected
  void sse_encode_list_daily_weather_forecast(
      List<DailyWeatherForecast> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hourly_weather_forecast(
      List<HourlyWeatherForecast> self, SseSerializer serializer);

  @protected
  void sse_encode_list_location(List<Location> self, SseSerializer serializer);

  @protected
  void sse_encode_list_location_entry(
      List<LocationEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_packing_list_entry(
      List<PackingListEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_packing_list_entry_condition(
      List<PackingListEntryCondition> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_transit(List<Transit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip(List<Trip> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_attachment(
      List<TripAttachment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_packing_list_entry(
      List<TripPackingListEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_location(Location self, SseSerializer serializer);

  @protected
  void sse_encode_location_entry(LocationEntry self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
      DateTime? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_trip(Trip? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_weather_forecast(
      WeatherForecast? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_packing_list_entry(
      PackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_packing_list_entry_condition(
      PackingListEntryCondition self, SseSerializer serializer);

  @protected
  void sse_encode_quantity(Quantity self, SseSerializer serializer);

  @protected
  void sse_encode_train(Train self, SseSerializer serializer);

  @protected
  void sse_encode_train_station(TrainStation self, SseSerializer serializer);

  @protected
  void sse_encode_transit(Transit self, SseSerializer serializer);

  @protected
  void sse_encode_trip(Trip self, SseSerializer serializer);

  @protected
  void sse_encode_trip_attachment(
      TripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_trip_packing_list_entry(
      TripPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_trip_packing_list_model(
      TripPackingListModel self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_weather_condition(
      WeatherCondition self, SseSerializer serializer);

  @protected
  void sse_encode_weather_forecast(
      WeatherForecast self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
