// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/accommodations.dart';
import 'api/attachments.dart';
import 'api/bookings.dart';
import 'api/packing_list.dart';
import 'api/points_of_interest.dart';
import 'api/tags.dart';
import 'api/timeline.dart';
import 'api/transits.dart';
import 'api/trips.dart';
import 'commands/add_accommodation_attachment.dart';
import 'commands/add_car_rental.dart';
import 'commands/add_packing_list_entry.dart';
import 'commands/add_reservation.dart';
import 'commands/add_tag_to_trip.dart';
import 'commands/add_train.dart';
import 'commands/add_trip_accommodation.dart';
import 'commands/add_trip_attachment.dart';
import 'commands/add_trip_location.dart';
import 'commands/add_trip_point_of_interest.dart';
import 'commands/create_tag.dart';
import 'commands/create_trip.dart';
import 'commands/delete_packing_list_entry.dart';
import 'commands/parse_shared_train_data.dart';
import 'commands/parse_train_data.dart';
import 'commands/remove_tag_from_trip.dart';
import 'commands/search_web_images.dart';
import 'commands/set_trip_tags.dart';
import 'commands/update_car_rental.dart';
import 'commands/update_packing_list_entry.dart';
import 'commands/update_reservation.dart';
import 'commands/update_tag.dart';
import 'commands/update_train.dart';
import 'commands/update_trip.dart';
import 'commands/update_trip_accommodation.dart';
import 'commands/update_trip_point_of_interest.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'models.dart';
import 'models/bookings.dart';
import 'models/point_of_interests.dart';
import 'models/tidal_information.dart';
import 'models/timeline.dart';
import 'models/transits.dart';
import 'models/web_images.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  AccommodationModel dco_decode_accommodation_model(dynamic raw);

  @protected
  AccommodationStatus dco_decode_accommodation_status(dynamic raw);

  @protected
  AccommodationStatusType dco_decode_accommodation_status_type(dynamic raw);

  @protected
  AddAccommodationAttachment dco_decode_add_accommodation_attachment(
      dynamic raw);

  @protected
  AddCarRental dco_decode_add_car_rental(dynamic raw);

  @protected
  AddPackingListEntry dco_decode_add_packing_list_entry(dynamic raw);

  @protected
  AddReservation dco_decode_add_reservation(dynamic raw);

  @protected
  AddTagToTrip dco_decode_add_tag_to_trip(dynamic raw);

  @protected
  AddTrain dco_decode_add_train(dynamic raw);

  @protected
  AddTripAccommodation dco_decode_add_trip_accommodation(dynamic raw);

  @protected
  AddTripAttachment dco_decode_add_trip_attachment(dynamic raw);

  @protected
  AddTripLocation dco_decode_add_trip_location(dynamic raw);

  @protected
  AddTripPointOfInterest dco_decode_add_trip_point_of_interest(dynamic raw);

  @protected
  AttachmentListModel dco_decode_attachment_list_model(dynamic raw);

  @protected
  Booking dco_decode_booking(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  AccommodationStatus dco_decode_box_autoadd_accommodation_status(dynamic raw);

  @protected
  AddAccommodationAttachment
      dco_decode_box_autoadd_add_accommodation_attachment(dynamic raw);

  @protected
  AddCarRental dco_decode_box_autoadd_add_car_rental(dynamic raw);

  @protected
  AddPackingListEntry dco_decode_box_autoadd_add_packing_list_entry(
      dynamic raw);

  @protected
  AddReservation dco_decode_box_autoadd_add_reservation(dynamic raw);

  @protected
  AddTagToTrip dco_decode_box_autoadd_add_tag_to_trip(dynamic raw);

  @protected
  AddTrain dco_decode_box_autoadd_add_train(dynamic raw);

  @protected
  AddTripAccommodation dco_decode_box_autoadd_add_trip_accommodation(
      dynamic raw);

  @protected
  AddTripAttachment dco_decode_box_autoadd_add_trip_attachment(dynamic raw);

  @protected
  AddTripLocation dco_decode_box_autoadd_add_trip_location(dynamic raw);

  @protected
  AddTripPointOfInterest dco_decode_box_autoadd_add_trip_point_of_interest(
      dynamic raw);

  @protected
  CarRental dco_decode_box_autoadd_car_rental(dynamic raw);

  @protected
  Coordinate dco_decode_box_autoadd_coordinate(dynamic raw);

  @protected
  CreateTag dco_decode_box_autoadd_create_tag(dynamic raw);

  @protected
  CreateTrip dco_decode_box_autoadd_create_trip(dynamic raw);

  @protected
  DeletePackingListEntry dco_decode_box_autoadd_delete_packing_list_entry(
      dynamic raw);

  @protected
  FlightOverviewModel dco_decode_box_autoadd_flight_overview_model(dynamic raw);

  @protected
  ImportParsedTrainJourney dco_decode_box_autoadd_import_parsed_train_journey(
      dynamic raw);

  @protected
  LocationEntry dco_decode_box_autoadd_location_entry(dynamic raw);

  @protected
  ParseTrainData dco_decode_box_autoadd_parse_train_data(dynamic raw);

  @protected
  RemoveTagFromTrip dco_decode_box_autoadd_remove_tag_from_trip(dynamic raw);

  @protected
  Reservation dco_decode_box_autoadd_reservation(dynamic raw);

  @protected
  SearchWebImages dco_decode_box_autoadd_search_web_images(dynamic raw);

  @protected
  SetTripTags dco_decode_box_autoadd_set_trip_tags(dynamic raw);

  @protected
  TagModel dco_decode_box_autoadd_tag_model(dynamic raw);

  @protected
  TrainOverviewModel dco_decode_box_autoadd_train_overview_model(dynamic raw);

  @protected
  TransitOverviewModel dco_decode_box_autoadd_transit_overview_model(
      dynamic raw);

  @protected
  TripLocationListModel dco_decode_box_autoadd_trip_location_list_model(
      dynamic raw);

  @protected
  UpdateCarRental dco_decode_box_autoadd_update_car_rental(dynamic raw);

  @protected
  UpdatePackingListEntry dco_decode_box_autoadd_update_packing_list_entry(
      dynamic raw);

  @protected
  UpdateReservation dco_decode_box_autoadd_update_reservation(dynamic raw);

  @protected
  UpdateTag dco_decode_box_autoadd_update_tag(dynamic raw);

  @protected
  UpdateTrain dco_decode_box_autoadd_update_train(dynamic raw);

  @protected
  UpdateTrip dco_decode_box_autoadd_update_trip(dynamic raw);

  @protected
  UpdateTripAccommodation dco_decode_box_autoadd_update_trip_accommodation(
      dynamic raw);

  @protected
  UpdateTripPointOfInterest
      dco_decode_box_autoadd_update_trip_point_of_interest(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  WeatherForecast dco_decode_box_autoadd_weather_forecast(dynamic raw);

  @protected
  CarRental dco_decode_car_rental(dynamic raw);

  @protected
  Coordinate dco_decode_coordinate(dynamic raw);

  @protected
  CreateTag dco_decode_create_tag(dynamic raw);

  @protected
  CreateTrip dco_decode_create_trip(dynamic raw);

  @protected
  DailyWeatherForecast dco_decode_daily_weather_forecast(dynamic raw);

  @protected
  DeletePackingListEntry dco_decode_delete_packing_list_entry(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FlightOverviewModel dco_decode_flight_overview_model(dynamic raw);

  @protected
  HourlyWeatherForecast dco_decode_hourly_weather_forecast(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportParsedTrainJourney dco_decode_import_parsed_train_journey(dynamic raw);

  @protected
  List<UuidValue> dco_decode_list_Uuid(dynamic raw);

  @protected
  List<AccommodationModel> dco_decode_list_accommodation_model(dynamic raw);

  @protected
  List<AttachmentListModel> dco_decode_list_attachment_list_model(dynamic raw);

  @protected
  List<Booking> dco_decode_list_booking(dynamic raw);

  @protected
  List<DailyWeatherForecast> dco_decode_list_daily_weather_forecast(
      dynamic raw);

  @protected
  List<HourlyWeatherForecast> dco_decode_list_hourly_weather_forecast(
      dynamic raw);

  @protected
  List<LocationEntry> dco_decode_list_location_entry(dynamic raw);

  @protected
  List<PackingListEntry> dco_decode_list_packing_list_entry(dynamic raw);

  @protected
  List<PackingListEntryCondition> dco_decode_list_packing_list_entry_condition(
      dynamic raw);

  @protected
  List<ParsedTrainSegment> dco_decode_list_parsed_train_segment(dynamic raw);

  @protected
  List<PointOfInterestModel> dco_decode_list_point_of_interest_model(
      dynamic raw);

  @protected
  List<PointOfInterestSearchModel>
      dco_decode_list_point_of_interest_search_model(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TagModel> dco_decode_list_tag_model(dynamic raw);

  @protected
  List<TidalInformation> dco_decode_list_tidal_information(dynamic raw);

  @protected
  List<TimelineItem> dco_decode_list_timeline_item(dynamic raw);

  @protected
  List<Train> dco_decode_list_train(dynamic raw);

  @protected
  List<TripAttachment> dco_decode_list_trip_attachment(dynamic raw);

  @protected
  List<TripListModel> dco_decode_list_trip_list_model(dynamic raw);

  @protected
  List<TripLocationListModel> dco_decode_list_trip_location_list_model(
      dynamic raw);

  @protected
  List<TripLocationSummary> dco_decode_list_trip_location_summary(dynamic raw);

  @protected
  List<TripPackingListEntry> dco_decode_list_trip_packing_list_entry(
      dynamic raw);

  @protected
  List<TripPackingListGroup> dco_decode_list_trip_packing_list_group(
      dynamic raw);

  @protected
  List<WebImage> dco_decode_list_web_image(dynamic raw);

  @protected
  LocationEntry dco_decode_location_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  AccommodationStatus? dco_decode_opt_box_autoadd_accommodation_status(
      dynamic raw);

  @protected
  Coordinate? dco_decode_opt_box_autoadd_coordinate(dynamic raw);

  @protected
  LocationEntry? dco_decode_opt_box_autoadd_location_entry(dynamic raw);

  @protected
  TagModel? dco_decode_opt_box_autoadd_tag_model(dynamic raw);

  @protected
  TransitOverviewModel? dco_decode_opt_box_autoadd_transit_overview_model(
      dynamic raw);

  @protected
  TripLocationListModel? dco_decode_opt_box_autoadd_trip_location_list_model(
      dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  WeatherForecast? dco_decode_opt_box_autoadd_weather_forecast(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PackingListEntry dco_decode_packing_list_entry(dynamic raw);

  @protected
  PackingListEntryCondition dco_decode_packing_list_entry_condition(
      dynamic raw);

  @protected
  ParseTrainData dco_decode_parse_train_data(dynamic raw);

  @protected
  ParsedTrainJourney dco_decode_parsed_train_journey(dynamic raw);

  @protected
  ParsedTrainSegment dco_decode_parsed_train_segment(dynamic raw);

  @protected
  PointOfInterestModel dco_decode_point_of_interest_model(dynamic raw);

  @protected
  PointOfInterestOsmModel dco_decode_point_of_interest_osm_model(dynamic raw);

  @protected
  PointOfInterestSearchModel dco_decode_point_of_interest_search_model(
      dynamic raw);

  @protected
  Quantity dco_decode_quantity(dynamic raw);

  @protected
  RemoveTagFromTrip dco_decode_remove_tag_from_trip(dynamic raw);

  @protected
  Reservation dco_decode_reservation(dynamic raw);

  @protected
  ReservationCategory dco_decode_reservation_category(dynamic raw);

  @protected
  SearchWebImages dco_decode_search_web_images(dynamic raw);

  @protected
  SetTripTags dco_decode_set_trip_tags(dynamic raw);

  @protected
  TagModel dco_decode_tag_model(dynamic raw);

  @protected
  TidalInformation dco_decode_tidal_information(dynamic raw);

  @protected
  TideType dco_decode_tide_type(dynamic raw);

  @protected
  TimelineItem dco_decode_timeline_item(dynamic raw);

  @protected
  TimelineItemDetails dco_decode_timeline_item_details(dynamic raw);

  @protected
  TimelineModel dco_decode_timeline_model(dynamic raw);

  @protected
  Train dco_decode_train(dynamic raw);

  @protected
  TrainOverviewModel dco_decode_train_overview_model(dynamic raw);

  @protected
  TrainStation dco_decode_train_station(dynamic raw);

  @protected
  TransitOverviewModel dco_decode_transit_overview_model(dynamic raw);

  @protected
  TripAttachment dco_decode_trip_attachment(dynamic raw);

  @protected
  TripListModel dco_decode_trip_list_model(dynamic raw);

  @protected
  TripLocationListModel dco_decode_trip_location_list_model(dynamic raw);

  @protected
  TripLocationSummary dco_decode_trip_location_summary(dynamic raw);

  @protected
  TripOverviewModel dco_decode_trip_overview_model(dynamic raw);

  @protected
  TripPackingListEntry dco_decode_trip_packing_list_entry(dynamic raw);

  @protected
  TripPackingListGroup dco_decode_trip_packing_list_group(dynamic raw);

  @protected
  TripPackingListModel dco_decode_trip_packing_list_model(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateCarRental dco_decode_update_car_rental(dynamic raw);

  @protected
  UpdatePackingListEntry dco_decode_update_packing_list_entry(dynamic raw);

  @protected
  UpdateReservation dco_decode_update_reservation(dynamic raw);

  @protected
  UpdateTag dco_decode_update_tag(dynamic raw);

  @protected
  UpdateTrain dco_decode_update_train(dynamic raw);

  @protected
  UpdateTrip dco_decode_update_trip(dynamic raw);

  @protected
  UpdateTripAccommodation dco_decode_update_trip_accommodation(dynamic raw);

  @protected
  UpdateTripPointOfInterest dco_decode_update_trip_point_of_interest(
      dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WeatherCondition dco_decode_weather_condition(dynamic raw);

  @protected
  WeatherForecast dco_decode_weather_forecast(dynamic raw);

  @protected
  WebImage dco_decode_web_image(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  AccommodationModel sse_decode_accommodation_model(
      SseDeserializer deserializer);

  @protected
  AccommodationStatus sse_decode_accommodation_status(
      SseDeserializer deserializer);

  @protected
  AccommodationStatusType sse_decode_accommodation_status_type(
      SseDeserializer deserializer);

  @protected
  AddAccommodationAttachment sse_decode_add_accommodation_attachment(
      SseDeserializer deserializer);

  @protected
  AddCarRental sse_decode_add_car_rental(SseDeserializer deserializer);

  @protected
  AddPackingListEntry sse_decode_add_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  AddReservation sse_decode_add_reservation(SseDeserializer deserializer);

  @protected
  AddTagToTrip sse_decode_add_tag_to_trip(SseDeserializer deserializer);

  @protected
  AddTrain sse_decode_add_train(SseDeserializer deserializer);

  @protected
  AddTripAccommodation sse_decode_add_trip_accommodation(
      SseDeserializer deserializer);

  @protected
  AddTripAttachment sse_decode_add_trip_attachment(
      SseDeserializer deserializer);

  @protected
  AddTripLocation sse_decode_add_trip_location(SseDeserializer deserializer);

  @protected
  AddTripPointOfInterest sse_decode_add_trip_point_of_interest(
      SseDeserializer deserializer);

  @protected
  AttachmentListModel sse_decode_attachment_list_model(
      SseDeserializer deserializer);

  @protected
  Booking sse_decode_booking(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  AccommodationStatus sse_decode_box_autoadd_accommodation_status(
      SseDeserializer deserializer);

  @protected
  AddAccommodationAttachment
      sse_decode_box_autoadd_add_accommodation_attachment(
          SseDeserializer deserializer);

  @protected
  AddCarRental sse_decode_box_autoadd_add_car_rental(
      SseDeserializer deserializer);

  @protected
  AddPackingListEntry sse_decode_box_autoadd_add_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  AddReservation sse_decode_box_autoadd_add_reservation(
      SseDeserializer deserializer);

  @protected
  AddTagToTrip sse_decode_box_autoadd_add_tag_to_trip(
      SseDeserializer deserializer);

  @protected
  AddTrain sse_decode_box_autoadd_add_train(SseDeserializer deserializer);

  @protected
  AddTripAccommodation sse_decode_box_autoadd_add_trip_accommodation(
      SseDeserializer deserializer);

  @protected
  AddTripAttachment sse_decode_box_autoadd_add_trip_attachment(
      SseDeserializer deserializer);

  @protected
  AddTripLocation sse_decode_box_autoadd_add_trip_location(
      SseDeserializer deserializer);

  @protected
  AddTripPointOfInterest sse_decode_box_autoadd_add_trip_point_of_interest(
      SseDeserializer deserializer);

  @protected
  CarRental sse_decode_box_autoadd_car_rental(SseDeserializer deserializer);

  @protected
  Coordinate sse_decode_box_autoadd_coordinate(SseDeserializer deserializer);

  @protected
  CreateTag sse_decode_box_autoadd_create_tag(SseDeserializer deserializer);

  @protected
  CreateTrip sse_decode_box_autoadd_create_trip(SseDeserializer deserializer);

  @protected
  DeletePackingListEntry sse_decode_box_autoadd_delete_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  FlightOverviewModel sse_decode_box_autoadd_flight_overview_model(
      SseDeserializer deserializer);

  @protected
  ImportParsedTrainJourney sse_decode_box_autoadd_import_parsed_train_journey(
      SseDeserializer deserializer);

  @protected
  LocationEntry sse_decode_box_autoadd_location_entry(
      SseDeserializer deserializer);

  @protected
  ParseTrainData sse_decode_box_autoadd_parse_train_data(
      SseDeserializer deserializer);

  @protected
  RemoveTagFromTrip sse_decode_box_autoadd_remove_tag_from_trip(
      SseDeserializer deserializer);

  @protected
  Reservation sse_decode_box_autoadd_reservation(SseDeserializer deserializer);

  @protected
  SearchWebImages sse_decode_box_autoadd_search_web_images(
      SseDeserializer deserializer);

  @protected
  SetTripTags sse_decode_box_autoadd_set_trip_tags(
      SseDeserializer deserializer);

  @protected
  TagModel sse_decode_box_autoadd_tag_model(SseDeserializer deserializer);

  @protected
  TrainOverviewModel sse_decode_box_autoadd_train_overview_model(
      SseDeserializer deserializer);

  @protected
  TransitOverviewModel sse_decode_box_autoadd_transit_overview_model(
      SseDeserializer deserializer);

  @protected
  TripLocationListModel sse_decode_box_autoadd_trip_location_list_model(
      SseDeserializer deserializer);

  @protected
  UpdateCarRental sse_decode_box_autoadd_update_car_rental(
      SseDeserializer deserializer);

  @protected
  UpdatePackingListEntry sse_decode_box_autoadd_update_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  UpdateReservation sse_decode_box_autoadd_update_reservation(
      SseDeserializer deserializer);

  @protected
  UpdateTag sse_decode_box_autoadd_update_tag(SseDeserializer deserializer);

  @protected
  UpdateTrain sse_decode_box_autoadd_update_train(SseDeserializer deserializer);

  @protected
  UpdateTrip sse_decode_box_autoadd_update_trip(SseDeserializer deserializer);

  @protected
  UpdateTripAccommodation sse_decode_box_autoadd_update_trip_accommodation(
      SseDeserializer deserializer);

  @protected
  UpdateTripPointOfInterest
      sse_decode_box_autoadd_update_trip_point_of_interest(
          SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WeatherForecast sse_decode_box_autoadd_weather_forecast(
      SseDeserializer deserializer);

  @protected
  CarRental sse_decode_car_rental(SseDeserializer deserializer);

  @protected
  Coordinate sse_decode_coordinate(SseDeserializer deserializer);

  @protected
  CreateTag sse_decode_create_tag(SseDeserializer deserializer);

  @protected
  CreateTrip sse_decode_create_trip(SseDeserializer deserializer);

  @protected
  DailyWeatherForecast sse_decode_daily_weather_forecast(
      SseDeserializer deserializer);

  @protected
  DeletePackingListEntry sse_decode_delete_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FlightOverviewModel sse_decode_flight_overview_model(
      SseDeserializer deserializer);

  @protected
  HourlyWeatherForecast sse_decode_hourly_weather_forecast(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportParsedTrainJourney sse_decode_import_parsed_train_journey(
      SseDeserializer deserializer);

  @protected
  List<UuidValue> sse_decode_list_Uuid(SseDeserializer deserializer);

  @protected
  List<AccommodationModel> sse_decode_list_accommodation_model(
      SseDeserializer deserializer);

  @protected
  List<AttachmentListModel> sse_decode_list_attachment_list_model(
      SseDeserializer deserializer);

  @protected
  List<Booking> sse_decode_list_booking(SseDeserializer deserializer);

  @protected
  List<DailyWeatherForecast> sse_decode_list_daily_weather_forecast(
      SseDeserializer deserializer);

  @protected
  List<HourlyWeatherForecast> sse_decode_list_hourly_weather_forecast(
      SseDeserializer deserializer);

  @protected
  List<LocationEntry> sse_decode_list_location_entry(
      SseDeserializer deserializer);

  @protected
  List<PackingListEntry> sse_decode_list_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  List<PackingListEntryCondition> sse_decode_list_packing_list_entry_condition(
      SseDeserializer deserializer);

  @protected
  List<ParsedTrainSegment> sse_decode_list_parsed_train_segment(
      SseDeserializer deserializer);

  @protected
  List<PointOfInterestModel> sse_decode_list_point_of_interest_model(
      SseDeserializer deserializer);

  @protected
  List<PointOfInterestSearchModel>
      sse_decode_list_point_of_interest_search_model(
          SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TagModel> sse_decode_list_tag_model(SseDeserializer deserializer);

  @protected
  List<TidalInformation> sse_decode_list_tidal_information(
      SseDeserializer deserializer);

  @protected
  List<TimelineItem> sse_decode_list_timeline_item(
      SseDeserializer deserializer);

  @protected
  List<Train> sse_decode_list_train(SseDeserializer deserializer);

  @protected
  List<TripAttachment> sse_decode_list_trip_attachment(
      SseDeserializer deserializer);

  @protected
  List<TripListModel> sse_decode_list_trip_list_model(
      SseDeserializer deserializer);

  @protected
  List<TripLocationListModel> sse_decode_list_trip_location_list_model(
      SseDeserializer deserializer);

  @protected
  List<TripLocationSummary> sse_decode_list_trip_location_summary(
      SseDeserializer deserializer);

  @protected
  List<TripPackingListEntry> sse_decode_list_trip_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  List<TripPackingListGroup> sse_decode_list_trip_packing_list_group(
      SseDeserializer deserializer);

  @protected
  List<WebImage> sse_decode_list_web_image(SseDeserializer deserializer);

  @protected
  LocationEntry sse_decode_location_entry(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  AccommodationStatus? sse_decode_opt_box_autoadd_accommodation_status(
      SseDeserializer deserializer);

  @protected
  Coordinate? sse_decode_opt_box_autoadd_coordinate(
      SseDeserializer deserializer);

  @protected
  LocationEntry? sse_decode_opt_box_autoadd_location_entry(
      SseDeserializer deserializer);

  @protected
  TagModel? sse_decode_opt_box_autoadd_tag_model(SseDeserializer deserializer);

  @protected
  TransitOverviewModel? sse_decode_opt_box_autoadd_transit_overview_model(
      SseDeserializer deserializer);

  @protected
  TripLocationListModel? sse_decode_opt_box_autoadd_trip_location_list_model(
      SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WeatherForecast? sse_decode_opt_box_autoadd_weather_forecast(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PackingListEntry sse_decode_packing_list_entry(SseDeserializer deserializer);

  @protected
  PackingListEntryCondition sse_decode_packing_list_entry_condition(
      SseDeserializer deserializer);

  @protected
  ParseTrainData sse_decode_parse_train_data(SseDeserializer deserializer);

  @protected
  ParsedTrainJourney sse_decode_parsed_train_journey(
      SseDeserializer deserializer);

  @protected
  ParsedTrainSegment sse_decode_parsed_train_segment(
      SseDeserializer deserializer);

  @protected
  PointOfInterestModel sse_decode_point_of_interest_model(
      SseDeserializer deserializer);

  @protected
  PointOfInterestOsmModel sse_decode_point_of_interest_osm_model(
      SseDeserializer deserializer);

  @protected
  PointOfInterestSearchModel sse_decode_point_of_interest_search_model(
      SseDeserializer deserializer);

  @protected
  Quantity sse_decode_quantity(SseDeserializer deserializer);

  @protected
  RemoveTagFromTrip sse_decode_remove_tag_from_trip(
      SseDeserializer deserializer);

  @protected
  Reservation sse_decode_reservation(SseDeserializer deserializer);

  @protected
  ReservationCategory sse_decode_reservation_category(
      SseDeserializer deserializer);

  @protected
  SearchWebImages sse_decode_search_web_images(SseDeserializer deserializer);

  @protected
  SetTripTags sse_decode_set_trip_tags(SseDeserializer deserializer);

  @protected
  TagModel sse_decode_tag_model(SseDeserializer deserializer);

  @protected
  TidalInformation sse_decode_tidal_information(SseDeserializer deserializer);

  @protected
  TideType sse_decode_tide_type(SseDeserializer deserializer);

  @protected
  TimelineItem sse_decode_timeline_item(SseDeserializer deserializer);

  @protected
  TimelineItemDetails sse_decode_timeline_item_details(
      SseDeserializer deserializer);

  @protected
  TimelineModel sse_decode_timeline_model(SseDeserializer deserializer);

  @protected
  Train sse_decode_train(SseDeserializer deserializer);

  @protected
  TrainOverviewModel sse_decode_train_overview_model(
      SseDeserializer deserializer);

  @protected
  TrainStation sse_decode_train_station(SseDeserializer deserializer);

  @protected
  TransitOverviewModel sse_decode_transit_overview_model(
      SseDeserializer deserializer);

  @protected
  TripAttachment sse_decode_trip_attachment(SseDeserializer deserializer);

  @protected
  TripListModel sse_decode_trip_list_model(SseDeserializer deserializer);

  @protected
  TripLocationListModel sse_decode_trip_location_list_model(
      SseDeserializer deserializer);

  @protected
  TripLocationSummary sse_decode_trip_location_summary(
      SseDeserializer deserializer);

  @protected
  TripOverviewModel sse_decode_trip_overview_model(
      SseDeserializer deserializer);

  @protected
  TripPackingListEntry sse_decode_trip_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  TripPackingListGroup sse_decode_trip_packing_list_group(
      SseDeserializer deserializer);

  @protected
  TripPackingListModel sse_decode_trip_packing_list_model(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateCarRental sse_decode_update_car_rental(SseDeserializer deserializer);

  @protected
  UpdatePackingListEntry sse_decode_update_packing_list_entry(
      SseDeserializer deserializer);

  @protected
  UpdateReservation sse_decode_update_reservation(SseDeserializer deserializer);

  @protected
  UpdateTag sse_decode_update_tag(SseDeserializer deserializer);

  @protected
  UpdateTrain sse_decode_update_train(SseDeserializer deserializer);

  @protected
  UpdateTrip sse_decode_update_trip(SseDeserializer deserializer);

  @protected
  UpdateTripAccommodation sse_decode_update_trip_accommodation(
      SseDeserializer deserializer);

  @protected
  UpdateTripPointOfInterest sse_decode_update_trip_point_of_interest(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WeatherCondition sse_decode_weather_condition(SseDeserializer deserializer);

  @protected
  WeatherForecast sse_decode_weather_forecast(SseDeserializer deserializer);

  @protected
  WebImage sse_decode_web_image(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_accommodation_model(
      AccommodationModel self, SseSerializer serializer);

  @protected
  void sse_encode_accommodation_status(
      AccommodationStatus self, SseSerializer serializer);

  @protected
  void sse_encode_accommodation_status_type(
      AccommodationStatusType self, SseSerializer serializer);

  @protected
  void sse_encode_add_accommodation_attachment(
      AddAccommodationAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_add_car_rental(AddCarRental self, SseSerializer serializer);

  @protected
  void sse_encode_add_packing_list_entry(
      AddPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_add_reservation(
      AddReservation self, SseSerializer serializer);

  @protected
  void sse_encode_add_tag_to_trip(AddTagToTrip self, SseSerializer serializer);

  @protected
  void sse_encode_add_train(AddTrain self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_accommodation(
      AddTripAccommodation self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_attachment(
      AddTripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_location(
      AddTripLocation self, SseSerializer serializer);

  @protected
  void sse_encode_add_trip_point_of_interest(
      AddTripPointOfInterest self, SseSerializer serializer);

  @protected
  void sse_encode_attachment_list_model(
      AttachmentListModel self, SseSerializer serializer);

  @protected
  void sse_encode_booking(Booking self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
      DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_accommodation_status(
      AccommodationStatus self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_accommodation_attachment(
      AddAccommodationAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_car_rental(
      AddCarRental self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_packing_list_entry(
      AddPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_reservation(
      AddReservation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_tag_to_trip(
      AddTagToTrip self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_train(
      AddTrain self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_accommodation(
      AddTripAccommodation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_attachment(
      AddTripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_location(
      AddTripLocation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_trip_point_of_interest(
      AddTripPointOfInterest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_car_rental(
      CarRental self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_coordinate(
      Coordinate self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_tag(
      CreateTag self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_trip(
      CreateTrip self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delete_packing_list_entry(
      DeletePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flight_overview_model(
      FlightOverviewModel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_import_parsed_train_journey(
      ImportParsedTrainJourney self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_location_entry(
      LocationEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_parse_train_data(
      ParseTrainData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_remove_tag_from_trip(
      RemoveTagFromTrip self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_reservation(
      Reservation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_search_web_images(
      SearchWebImages self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_set_trip_tags(
      SetTripTags self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tag_model(
      TagModel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_train_overview_model(
      TrainOverviewModel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transit_overview_model(
      TransitOverviewModel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_trip_location_list_model(
      TripLocationListModel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_car_rental(
      UpdateCarRental self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_packing_list_entry(
      UpdatePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_reservation(
      UpdateReservation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_tag(
      UpdateTag self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_train(
      UpdateTrain self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_trip(
      UpdateTrip self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_trip_accommodation(
      UpdateTripAccommodation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_trip_point_of_interest(
      UpdateTripPointOfInterest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_weather_forecast(
      WeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_car_rental(CarRental self, SseSerializer serializer);

  @protected
  void sse_encode_coordinate(Coordinate self, SseSerializer serializer);

  @protected
  void sse_encode_create_tag(CreateTag self, SseSerializer serializer);

  @protected
  void sse_encode_create_trip(CreateTrip self, SseSerializer serializer);

  @protected
  void sse_encode_daily_weather_forecast(
      DailyWeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_delete_packing_list_entry(
      DeletePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_flight_overview_model(
      FlightOverviewModel self, SseSerializer serializer);

  @protected
  void sse_encode_hourly_weather_forecast(
      HourlyWeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_parsed_train_journey(
      ImportParsedTrainJourney self, SseSerializer serializer);

  @protected
  void sse_encode_list_Uuid(List<UuidValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_accommodation_model(
      List<AccommodationModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_attachment_list_model(
      List<AttachmentListModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_booking(List<Booking> self, SseSerializer serializer);

  @protected
  void sse_encode_list_daily_weather_forecast(
      List<DailyWeatherForecast> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hourly_weather_forecast(
      List<HourlyWeatherForecast> self, SseSerializer serializer);

  @protected
  void sse_encode_list_location_entry(
      List<LocationEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_packing_list_entry(
      List<PackingListEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_packing_list_entry_condition(
      List<PackingListEntryCondition> self, SseSerializer serializer);

  @protected
  void sse_encode_list_parsed_train_segment(
      List<ParsedTrainSegment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_point_of_interest_model(
      List<PointOfInterestModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_point_of_interest_search_model(
      List<PointOfInterestSearchModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_model(List<TagModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tidal_information(
      List<TidalInformation> self, SseSerializer serializer);

  @protected
  void sse_encode_list_timeline_item(
      List<TimelineItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_train(List<Train> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_attachment(
      List<TripAttachment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_list_model(
      List<TripListModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_location_list_model(
      List<TripLocationListModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_location_summary(
      List<TripLocationSummary> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_packing_list_entry(
      List<TripPackingListEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trip_packing_list_group(
      List<TripPackingListGroup> self, SseSerializer serializer);

  @protected
  void sse_encode_list_web_image(List<WebImage> self, SseSerializer serializer);

  @protected
  void sse_encode_location_entry(LocationEntry self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
      DateTime? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_accommodation_status(
      AccommodationStatus? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_coordinate(
      Coordinate? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_location_entry(
      LocationEntry? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_tag_model(
      TagModel? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_transit_overview_model(
      TransitOverviewModel? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_trip_location_list_model(
      TripLocationListModel? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_weather_forecast(
      WeatherForecast? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_packing_list_entry(
      PackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_packing_list_entry_condition(
      PackingListEntryCondition self, SseSerializer serializer);

  @protected
  void sse_encode_parse_train_data(
      ParseTrainData self, SseSerializer serializer);

  @protected
  void sse_encode_parsed_train_journey(
      ParsedTrainJourney self, SseSerializer serializer);

  @protected
  void sse_encode_parsed_train_segment(
      ParsedTrainSegment self, SseSerializer serializer);

  @protected
  void sse_encode_point_of_interest_model(
      PointOfInterestModel self, SseSerializer serializer);

  @protected
  void sse_encode_point_of_interest_osm_model(
      PointOfInterestOsmModel self, SseSerializer serializer);

  @protected
  void sse_encode_point_of_interest_search_model(
      PointOfInterestSearchModel self, SseSerializer serializer);

  @protected
  void sse_encode_quantity(Quantity self, SseSerializer serializer);

  @protected
  void sse_encode_remove_tag_from_trip(
      RemoveTagFromTrip self, SseSerializer serializer);

  @protected
  void sse_encode_reservation(Reservation self, SseSerializer serializer);

  @protected
  void sse_encode_reservation_category(
      ReservationCategory self, SseSerializer serializer);

  @protected
  void sse_encode_search_web_images(
      SearchWebImages self, SseSerializer serializer);

  @protected
  void sse_encode_set_trip_tags(SetTripTags self, SseSerializer serializer);

  @protected
  void sse_encode_tag_model(TagModel self, SseSerializer serializer);

  @protected
  void sse_encode_tidal_information(
      TidalInformation self, SseSerializer serializer);

  @protected
  void sse_encode_tide_type(TideType self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_item(TimelineItem self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_item_details(
      TimelineItemDetails self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_model(TimelineModel self, SseSerializer serializer);

  @protected
  void sse_encode_train(Train self, SseSerializer serializer);

  @protected
  void sse_encode_train_overview_model(
      TrainOverviewModel self, SseSerializer serializer);

  @protected
  void sse_encode_train_station(TrainStation self, SseSerializer serializer);

  @protected
  void sse_encode_transit_overview_model(
      TransitOverviewModel self, SseSerializer serializer);

  @protected
  void sse_encode_trip_attachment(
      TripAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_trip_list_model(TripListModel self, SseSerializer serializer);

  @protected
  void sse_encode_trip_location_list_model(
      TripLocationListModel self, SseSerializer serializer);

  @protected
  void sse_encode_trip_location_summary(
      TripLocationSummary self, SseSerializer serializer);

  @protected
  void sse_encode_trip_overview_model(
      TripOverviewModel self, SseSerializer serializer);

  @protected
  void sse_encode_trip_packing_list_entry(
      TripPackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_trip_packing_list_group(
      TripPackingListGroup self, SseSerializer serializer);

  @protected
  void sse_encode_trip_packing_list_model(
      TripPackingListModel self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_car_rental(
      UpdateCarRental self, SseSerializer serializer);

  @protected
  void sse_encode_update_packing_list_entry(
      UpdatePackingListEntry self, SseSerializer serializer);

  @protected
  void sse_encode_update_reservation(
      UpdateReservation self, SseSerializer serializer);

  @protected
  void sse_encode_update_tag(UpdateTag self, SseSerializer serializer);

  @protected
  void sse_encode_update_train(UpdateTrain self, SseSerializer serializer);

  @protected
  void sse_encode_update_trip(UpdateTrip self, SseSerializer serializer);

  @protected
  void sse_encode_update_trip_accommodation(
      UpdateTripAccommodation self, SseSerializer serializer);

  @protected
  void sse_encode_update_trip_point_of_interest(
      UpdateTripPointOfInterest self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_weather_condition(
      WeatherCondition self, SseSerializer serializer);

  @protected
  void sse_encode_weather_forecast(
      WeatherForecast self, SseSerializer serializer);

  @protected
  void sse_encode_web_image(WebImage self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
