// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'models.freezed.dart';

class AccommodationModel {
  final UuidValue id;
  final String name;
  final String? address;
  final DateTime checkIn;
  final DateTime checkOut;
  final List<TripAttachment> attachments;

  const AccommodationModel({
    required this.id,
    required this.name,
    this.address,
    required this.checkIn,
    required this.checkOut,
    required this.attachments,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      address.hashCode ^
      checkIn.hashCode ^
      checkOut.hashCode ^
      attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccommodationModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          address == other.address &&
          checkIn == other.checkIn &&
          checkOut == other.checkOut &&
          attachments == other.attachments;
}

class AttachmentListModel {
  final UuidValue id;
  final String name;
  final String fileName;
  final String contentType;

  const AttachmentListModel({
    required this.id,
    required this.name,
    required this.fileName,
    required this.contentType,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ fileName.hashCode ^ contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentListModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          fileName == other.fileName &&
          contentType == other.contentType;
}

class Coordinates {
  final double latitude;
  final double longitude;

  const Coordinates({
    required this.latitude,
    required this.longitude,
  });

  @override
  int get hashCode => latitude.hashCode ^ longitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Coordinates &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude;
}

class DailyWeatherForecast {
  final DateTime day;
  final double minTemperature;
  final double maxTemperature;
  final double morningTemperature;
  final double dayTemperature;
  final double eveningTemperature;
  final double nightTemperature;
  final WeatherCondition condition;

  /// mm
  final double precipitationAmount;
  final double precipitationProbability;
  final double windSpeed;

  const DailyWeatherForecast({
    required this.day,
    required this.minTemperature,
    required this.maxTemperature,
    required this.morningTemperature,
    required this.dayTemperature,
    required this.eveningTemperature,
    required this.nightTemperature,
    required this.condition,
    required this.precipitationAmount,
    required this.precipitationProbability,
    required this.windSpeed,
  });

  @override
  int get hashCode =>
      day.hashCode ^
      minTemperature.hashCode ^
      maxTemperature.hashCode ^
      morningTemperature.hashCode ^
      dayTemperature.hashCode ^
      eveningTemperature.hashCode ^
      nightTemperature.hashCode ^
      condition.hashCode ^
      precipitationAmount.hashCode ^
      precipitationProbability.hashCode ^
      windSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyWeatherForecast &&
          runtimeType == other.runtimeType &&
          day == other.day &&
          minTemperature == other.minTemperature &&
          maxTemperature == other.maxTemperature &&
          morningTemperature == other.morningTemperature &&
          dayTemperature == other.dayTemperature &&
          eveningTemperature == other.eveningTemperature &&
          nightTemperature == other.nightTemperature &&
          condition == other.condition &&
          precipitationAmount == other.precipitationAmount &&
          precipitationProbability == other.precipitationProbability &&
          windSpeed == other.windSpeed;
}

class HourlyWeatherForecast {
  final DateTime time;
  final double temperature;
  final double windSpeed;

  /// mm/h
  final double precipitationAmount;
  final double precipitationProbability;
  final WeatherCondition condition;

  const HourlyWeatherForecast({
    required this.time,
    required this.temperature,
    required this.windSpeed,
    required this.precipitationAmount,
    required this.precipitationProbability,
    required this.condition,
  });

  @override
  int get hashCode =>
      time.hashCode ^
      temperature.hashCode ^
      windSpeed.hashCode ^
      precipitationAmount.hashCode ^
      precipitationProbability.hashCode ^
      condition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HourlyWeatherForecast &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          temperature == other.temperature &&
          windSpeed == other.windSpeed &&
          precipitationAmount == other.precipitationAmount &&
          precipitationProbability == other.precipitationProbability &&
          condition == other.condition;
}

class LocationEntry {
  final String name;
  final Coordinates coordinates;
  final String country;

  const LocationEntry({
    required this.name,
    required this.coordinates,
    required this.country,
  });

  @override
  int get hashCode => name.hashCode ^ coordinates.hashCode ^ country.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocationEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          coordinates == other.coordinates &&
          country == other.country;
}

class PackingListEntry {
  final UuidValue id;
  final String name;
  final String? description;
  final List<PackingListEntryCondition> conditions;
  final Quantity quantity;
  final String? category;

  const PackingListEntry({
    required this.id,
    required this.name,
    this.description,
    required this.conditions,
    required this.quantity,
    this.category,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      conditions.hashCode ^
      quantity.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackingListEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          conditions == other.conditions &&
          quantity == other.quantity &&
          category == other.category;
}

@freezed
sealed class PackingListEntryCondition with _$PackingListEntryCondition {
  const PackingListEntryCondition._();

  const factory PackingListEntryCondition.minTripDuration({
    required int length,
  }) = PackingListEntryCondition_MinTripDuration;
  const factory PackingListEntryCondition.maxTripDuration({
    required int length,
  }) = PackingListEntryCondition_MaxTripDuration;
  const factory PackingListEntryCondition.minTemperature({
    required double temperature,
  }) = PackingListEntryCondition_MinTemperature;
  const factory PackingListEntryCondition.maxTemperature({
    required double temperature,
  }) = PackingListEntryCondition_MaxTemperature;
  const factory PackingListEntryCondition.weather({
    required WeatherCondition condition,
    required double minProbability,
  }) = PackingListEntryCondition_Weather;
  const factory PackingListEntryCondition.tag({
    required String tag,
  }) = PackingListEntryCondition_Tag;
}

class Quantity {
  final BigInt? perDay;
  final BigInt? perNight;
  final BigInt? fixed;

  const Quantity({
    this.perDay,
    this.perNight,
    this.fixed,
  });

  @override
  int get hashCode => perDay.hashCode ^ perNight.hashCode ^ fixed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Quantity &&
          runtimeType == other.runtimeType &&
          perDay == other.perDay &&
          perNight == other.perNight &&
          fixed == other.fixed;
}

class TripAttachment {
  final UuidValue id;
  final String name;
  final String fileName;
  final String contentType;

  const TripAttachment({
    required this.id,
    required this.name,
    required this.fileName,
    required this.contentType,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ fileName.hashCode ^ contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripAttachment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          fileName == other.fileName &&
          contentType == other.contentType;
}

class TripListModel {
  final UuidValue id;
  final String name;
  final DateTime startDate;
  final DateTime endDate;
  final Uint8List? headerImage;

  const TripListModel({
    required this.id,
    required this.name,
    required this.startDate,
    required this.endDate,
    this.headerImage,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      headerImage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripListModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          headerImage == other.headerImage;
}

class TripLocationListModel {
  final UuidValue id;
  final Coordinates coordinates;
  final String city;
  final String country;
  final WeatherForecast? forecast;

  const TripLocationListModel({
    required this.id,
    required this.coordinates,
    required this.city,
    required this.country,
    this.forecast,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      coordinates.hashCode ^
      city.hashCode ^
      country.hashCode ^
      forecast.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripLocationListModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          coordinates == other.coordinates &&
          city == other.city &&
          country == other.country &&
          forecast == other.forecast;
}

class TripOverviewModel {
  final UuidValue id;
  final String name;
  final Uint8List? headerImage;
  final BigInt pendingPackingListItems;
  final BigInt packedPackingListItems;
  final BigInt totalPackingListItems;

  const TripOverviewModel({
    required this.id,
    required this.name,
    this.headerImage,
    required this.pendingPackingListItems,
    required this.packedPackingListItems,
    required this.totalPackingListItems,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      headerImage.hashCode ^
      pendingPackingListItems.hashCode ^
      packedPackingListItems.hashCode ^
      totalPackingListItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripOverviewModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          headerImage == other.headerImage &&
          pendingPackingListItems == other.pendingPackingListItems &&
          packedPackingListItems == other.packedPackingListItems &&
          totalPackingListItems == other.totalPackingListItems;
}

class TripPackingListEntry {
  final PackingListEntry packingListEntry;
  final bool isPacked;
  final BigInt? quantity;

  const TripPackingListEntry({
    required this.packingListEntry,
    required this.isPacked,
    this.quantity,
  });

  @override
  int get hashCode =>
      packingListEntry.hashCode ^ isPacked.hashCode ^ quantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripPackingListEntry &&
          runtimeType == other.runtimeType &&
          packingListEntry == other.packingListEntry &&
          isPacked == other.isPacked &&
          quantity == other.quantity;
}

class TripPackingListGroup {
  final UuidValue id;
  final String name;
  final List<TripPackingListEntry> entries;

  const TripPackingListGroup({
    required this.id,
    required this.name,
    required this.entries,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripPackingListGroup &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          entries == other.entries;
}

class TripPackingListModel {
  final List<TripPackingListGroup> groups;
  final List<TripPackingListEntry> entries;

  const TripPackingListModel({
    required this.groups,
    required this.entries,
  });

  @override
  int get hashCode => groups.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripPackingListModel &&
          runtimeType == other.runtimeType &&
          groups == other.groups &&
          entries == other.entries;
}

enum WeatherCondition {
  thunderstorm,
  sunny,
  rain,
  clouds,
  snow,
  ;
}

class WeatherForecast {
  final List<HourlyWeatherForecast> hourlyForecast;
  final List<DailyWeatherForecast> dailyForecast;

  const WeatherForecast({
    required this.hourlyForecast,
    required this.dailyForecast,
  });

  @override
  int get hashCode => hourlyForecast.hashCode ^ dailyForecast.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherForecast &&
          runtimeType == other.runtimeType &&
          hourlyForecast == other.hourlyForecast &&
          dailyForecast == other.dailyForecast;
}
