// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class AddAccommodationAttachment {
  final UuidValue accommodationId;
  final String name;
  final String path;

  const AddAccommodationAttachment({
    required this.accommodationId,
    required this.name,
    required this.path,
  });

  @override
  int get hashCode => accommodationId.hashCode ^ name.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddAccommodationAttachment &&
          runtimeType == other.runtimeType &&
          accommodationId == other.accommodationId &&
          name == other.name &&
          path == other.path;
}
