// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class AddTripAttachment {
  final UuidValue tripId;
  final String name;
  final String path;

  const AddTripAttachment({
    required this.tripId,
    required this.name,
    required this.path,
  });

  @override
  int get hashCode => tripId.hashCode ^ name.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddTripAttachment &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          name == other.name &&
          path == other.path;
}
