// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class AddTrain {
  final UuidValue tripId;
  final String? trainNumber;
  final String departureStationName;
  final String? departureStationCity;
  final String? departureStationCountry;
  final String departureScheduledPlatform;
  final String arrivalStationName;
  final String? arrivalStationCity;
  final String? arrivalStationCountry;
  final String arrivalScheduledPlatform;
  final DateTime scheduledDepartureTime;
  final DateTime scheduledArrivalTime;

  const AddTrain({
    required this.tripId,
    this.trainNumber,
    required this.departureStationName,
    this.departureStationCity,
    this.departureStationCountry,
    required this.departureScheduledPlatform,
    required this.arrivalStationName,
    this.arrivalStationCity,
    this.arrivalStationCountry,
    required this.arrivalScheduledPlatform,
    required this.scheduledDepartureTime,
    required this.scheduledArrivalTime,
  });

  @override
  int get hashCode =>
      tripId.hashCode ^
      trainNumber.hashCode ^
      departureStationName.hashCode ^
      departureStationCity.hashCode ^
      departureStationCountry.hashCode ^
      departureScheduledPlatform.hashCode ^
      arrivalStationName.hashCode ^
      arrivalStationCity.hashCode ^
      arrivalStationCountry.hashCode ^
      arrivalScheduledPlatform.hashCode ^
      scheduledDepartureTime.hashCode ^
      scheduledArrivalTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddTrain &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          trainNumber == other.trainNumber &&
          departureStationName == other.departureStationName &&
          departureStationCity == other.departureStationCity &&
          departureStationCountry == other.departureStationCountry &&
          departureScheduledPlatform == other.departureScheduledPlatform &&
          arrivalStationName == other.arrivalStationName &&
          arrivalStationCity == other.arrivalStationCity &&
          arrivalStationCountry == other.arrivalStationCountry &&
          arrivalScheduledPlatform == other.arrivalScheduledPlatform &&
          scheduledDepartureTime == other.scheduledDepartureTime &&
          scheduledArrivalTime == other.scheduledArrivalTime;
}
