// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class AddTripLocation {
  final UuidValue tripId;
  final LocationEntry location;

  const AddTripLocation({
    required this.tripId,
    required this.location,
  });

  @override
  int get hashCode => tripId.hashCode ^ location.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddTripLocation &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          location == other.location;
}
