// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class AddTripAccommodation {
  final UuidValue tripId;
  final String name;
  final DateTime? checkIn;
  final DateTime? checkOut;
  final String? address;

  const AddTripAccommodation({
    required this.tripId,
    required this.name,
    this.checkIn,
    this.checkOut,
    this.address,
  });

  @override
  int get hashCode =>
      tripId.hashCode ^
      name.hashCode ^
      checkIn.hashCode ^
      checkOut.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddTripAccommodation &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          name == other.name &&
          checkIn == other.checkIn &&
          checkOut == other.checkOut &&
          address == other.address;
}
