// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class AddTripPointOfInterest {
  final UuidValue tripId;
  final String name;
  final String address;
  final String? website;
  final String? openingHours;
  final String? price;
  final String? phoneNumber;
  final String? note;
  final Coordinate? coordinate;

  const AddTripPointOfInterest({
    required this.tripId,
    required this.name,
    required this.address,
    this.website,
    this.openingHours,
    this.price,
    this.phoneNumber,
    this.note,
    this.coordinate,
  });

  @override
  int get hashCode =>
      tripId.hashCode ^
      name.hashCode ^
      address.hashCode ^
      website.hashCode ^
      openingHours.hashCode ^
      price.hashCode ^
      phoneNumber.hashCode ^
      note.hashCode ^
      coordinate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddTripPointOfInterest &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          name == other.name &&
          address == other.address &&
          website == other.website &&
          openingHours == other.openingHours &&
          price == other.price &&
          phoneNumber == other.phoneNumber &&
          note == other.note &&
          coordinate == other.coordinate;
}
