// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CreateTrip {
  final String name;
  final DateTime startDate;
  final DateTime endDate;
  final Uint8List? headerImage;

  const CreateTrip({
    required this.name,
    required this.startDate,
    required this.endDate,
    this.headerImage,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      headerImage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateTrip &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          headerImage == other.headerImage;
}
