// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class ParseSharedTrainData {
  final UuidValue tripId;
  final String sharedText;

  const ParseSharedTrainData({
    required this.tripId,
    required this.sharedText,
  });

  @override
  int get hashCode => tripId.hashCode ^ sharedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseSharedTrainData &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          sharedText == other.sharedText;
}
