// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/transits.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class ImportParsedTrainJourney {
  final UuidValue tripId;
  final ParsedTrainJourney journey;

  const ImportParsedTrainJourney({
    required this.tripId,
    required this.journey,
  });

  @override
  int get hashCode => tripId.hashCode ^ journey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportParsedTrainJourney &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          journey == other.journey;
}
