// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SearchWebImages {
  final String query;

  const SearchWebImages({
    required this.query,
  });

  @override
  int get hashCode => query.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchWebImages &&
          runtimeType == other.runtimeType &&
          query == other.query;
}
