// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class SetTripTags {
  final UuidValue tripId;
  final List<UuidValue> tagIds;

  const SetTripTags({
    required this.tripId,
    required this.tagIds,
  });

  @override
  int get hashCode => tripId.hashCode ^ tagIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetTripTags &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          tagIds == other.tagIds;
}
