// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class AddTripDayLocation {
  final UuidValue tripId;
  final DateTime date;
  final UuidValue locationId;

  const AddTripDayLocation({
    required this.tripId,
    required this.date,
    required this.locationId,
  });

  @override
  int get hashCode => tripId.hashCode ^ date.hashCode ^ locationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddTripDayLocation &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          date == other.date &&
          locationId == other.locationId;
}

class AssignItemToDay {
  final UuidValue tripId;
  final SchedulableItemType itemType;
  final UuidValue itemId;
  final DateTime date;
  final DateTime? scheduledAt;

  const AssignItemToDay({
    required this.tripId,
    required this.itemType,
    required this.itemId,
    required this.date,
    this.scheduledAt,
  });

  @override
  int get hashCode =>
      tripId.hashCode ^
      itemType.hashCode ^
      itemId.hashCode ^
      date.hashCode ^
      scheduledAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssignItemToDay &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          itemType == other.itemType &&
          itemId == other.itemId &&
          date == other.date &&
          scheduledAt == other.scheduledAt;
}

class OrderedItem {
  final SchedulableItemType itemType;
  final UuidValue itemId;

  const OrderedItem({
    required this.itemType,
    required this.itemId,
  });

  @override
  int get hashCode => itemType.hashCode ^ itemId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderedItem &&
          runtimeType == other.runtimeType &&
          itemType == other.itemType &&
          itemId == other.itemId;
}

class RemoveTripDayLocation {
  final UuidValue tripDayId;
  final UuidValue locationId;

  const RemoveTripDayLocation({
    required this.tripDayId,
    required this.locationId,
  });

  @override
  int get hashCode => tripDayId.hashCode ^ locationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoveTripDayLocation &&
          runtimeType == other.runtimeType &&
          tripDayId == other.tripDayId &&
          locationId == other.locationId;
}

class ReorderDay {
  final UuidValue tripDayId;
  final List<OrderedItem> orderedItems;

  const ReorderDay({
    required this.tripDayId,
    required this.orderedItems,
  });

  @override
  int get hashCode => tripDayId.hashCode ^ orderedItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReorderDay &&
          runtimeType == other.runtimeType &&
          tripDayId == other.tripDayId &&
          orderedItems == other.orderedItems;
}

enum SchedulableItemType {
  pointOfInterest,
  route,
  ;
}

class SetPrimaryTripDayLocation {
  final UuidValue tripDayId;
  final UuidValue locationId;

  const SetPrimaryTripDayLocation({
    required this.tripDayId,
    required this.locationId,
  });

  @override
  int get hashCode => tripDayId.hashCode ^ locationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetPrimaryTripDayLocation &&
          runtimeType == other.runtimeType &&
          tripDayId == other.tripDayId &&
          locationId == other.locationId;
}

class SetTripDayTitle {
  final UuidValue tripId;
  final DateTime date;
  final String? title;

  const SetTripDayTitle({
    required this.tripId,
    required this.date,
    this.title,
  });

  @override
  int get hashCode => tripId.hashCode ^ date.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetTripDayTitle &&
          runtimeType == other.runtimeType &&
          tripId == other.tripId &&
          date == other.date &&
          title == other.title;
}

class UnassignItem {
  final SchedulableItemType itemType;
  final UuidValue itemId;

  const UnassignItem({
    required this.itemType,
    required this.itemId,
  });

  @override
  int get hashCode => itemType.hashCode ^ itemId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnassignItem &&
          runtimeType == other.runtimeType &&
          itemType == other.itemType &&
          itemId == other.itemId;
}
