// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class UpdateTripAccommodation {
  final UuidValue id;
  final String name;
  final String? address;
  final Coordinate? coordinate;
  final DateTime checkIn;
  final DateTime checkOut;

  const UpdateTripAccommodation({
    required this.id,
    required this.name,
    this.address,
    this.coordinate,
    required this.checkIn,
    required this.checkOut,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      address.hashCode ^
      coordinate.hashCode ^
      checkIn.hashCode ^
      checkOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateTripAccommodation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          address == other.address &&
          coordinate == other.coordinate &&
          checkIn == other.checkIn &&
          checkOut == other.checkOut;
}
