// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class UpdateRoute {
  final UuidValue id;
  final String? note;

  const UpdateRoute({
    required this.id,
    this.note,
  });

  @override
  int get hashCode => id.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateRoute &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          note == other.note;
}
