// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class UpdateTripPointOfInterest {
  final UuidValue id;
  final String name;
  final String address;
  final String? website;
  final String? openingHours;
  final String? price;

  const UpdateTripPointOfInterest({
    required this.id,
    required this.name,
    required this.address,
    this.website,
    this.openingHours,
    this.price,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      address.hashCode ^
      website.hashCode ^
      openingHours.hashCode ^
      price.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateTripPointOfInterest &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          address == other.address &&
          website == other.website &&
          openingHours == other.openingHours &&
          price == other.price;
}
