// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class UpdateCarRental {
  final UuidValue id;
  final String provider;
  final DateTime pickUpDate;
  final String pickUpLocation;
  final DateTime returnDate;
  final String? returnLocation;
  final String? bookingNumber;

  const UpdateCarRental({
    required this.id,
    required this.provider,
    required this.pickUpDate,
    required this.pickUpLocation,
    required this.returnDate,
    this.returnLocation,
    this.bookingNumber,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      provider.hashCode ^
      pickUpDate.hashCode ^
      pickUpLocation.hashCode ^
      returnDate.hashCode ^
      returnLocation.hashCode ^
      bookingNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateCarRental &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          provider == other.provider &&
          pickUpDate == other.pickUpDate &&
          pickUpLocation == other.pickUpLocation &&
          returnDate == other.returnDate &&
          returnLocation == other.returnLocation &&
          bookingNumber == other.bookingNumber;
}
