// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class UpdateReservation {
  final UuidValue id;
  final String title;
  final String? address;
  final DateTime startDate;
  final DateTime? endDate;
  final String? link;
  final String? bookingNumber;

  const UpdateReservation({
    required this.id,
    required this.title,
    this.address,
    required this.startDate,
    this.endDate,
    this.link,
    this.bookingNumber,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      address.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      link.hashCode ^
      bookingNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateReservation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          address == other.address &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          link == other.link &&
          bookingNumber == other.bookingNumber;
}
