// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class UpdatePackingListEntry {
  final UuidValue id;
  final String name;
  final String? description;
  final List<PackingListEntryCondition> conditions;
  final Quantity quantity;
  final String? category;

  const UpdatePackingListEntry({
    required this.id,
    required this.name,
    this.description,
    required this.conditions,
    required this.quantity,
    this.category,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      conditions.hashCode ^
      quantity.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdatePackingListEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          conditions == other.conditions &&
          quantity == other.quantity &&
          category == other.category;
}
