// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Return the most recent activity log entries for a trip, joined with
/// profile info for the actor. `limit` defaults to 50 if 0 is passed.
Future<List<TripActivityEntry>> listTripActivity(
        {required UuidValue tripId, required int limit}) =>
    RustLib.instance.api
        .crateApiActivityListTripActivity(tripId: tripId, limit: limit);

enum TripActivityAction {
  insert,
  update,
  delete,
  ;
}

class TripActivityEntry {
  final TripActivityKind kind;
  final UuidValue entityId;
  final String? label;
  final TripActivityAction action;
  final DateTime occurredAt;
  final UuidValue? userId;
  final String? userEmail;
  final String? userDisplayName;

  const TripActivityEntry({
    required this.kind,
    required this.entityId,
    this.label,
    required this.action,
    required this.occurredAt,
    this.userId,
    this.userEmail,
    this.userDisplayName,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      entityId.hashCode ^
      label.hashCode ^
      action.hashCode ^
      occurredAt.hashCode ^
      userId.hashCode ^
      userEmail.hashCode ^
      userDisplayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripActivityEntry &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          entityId == other.entityId &&
          label == other.label &&
          action == other.action &&
          occurredAt == other.occurredAt &&
          userId == other.userId &&
          userEmail == other.userEmail &&
          userDisplayName == other.userDisplayName;
}

enum TripActivityKind {
  trip,
  accommodation,
  location,
  reservation,
  carRental,
  pointOfInterest,
  train,
  other,
  ;
}
