// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../commands/add_trip_attachment.dart';
import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<List<AttachmentListModel>> getTripAttachments(
        {required UuidValue tripId}) =>
    RustLib.instance.api.crateApiAttachmentsGetTripAttachments(tripId: tripId);

Future<void> addTripAttachment({required AddTripAttachment command}) =>
    RustLib.instance.api.crateApiAttachmentsAddTripAttachment(command: command);

Future<void> readAttachment(
        {required UuidValue attachmentId, required String targetPath}) =>
    RustLib.instance.api.crateApiAttachmentsReadAttachment(
        attachmentId: attachmentId, targetPath: targetPath);

Future<void> deleteAttachment({required UuidValue attachmentId}) =>
    RustLib.instance.api
        .crateApiAttachmentsDeleteAttachment(attachmentId: attachmentId);
