// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../commands/add_car_rental.dart';
import '../commands/add_reservation.dart';
import '../commands/update_car_rental.dart';
import '../commands/update_reservation.dart';
import '../frb_generated.dart';
import '../models.dart';
import '../models/bookings.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<void> addReservation({required AddReservation command}) =>
    RustLib.instance.api.crateApiBookingsAddReservation(command: command);

Future<void> updateReservation({required UpdateReservation command}) =>
    RustLib.instance.api.crateApiBookingsUpdateReservation(command: command);

Future<void> deleteReservation({required UuidValue reservationId}) =>
    RustLib.instance.api
        .crateApiBookingsDeleteReservation(reservationId: reservationId);

Future<void> addCarRental({required AddCarRental command}) =>
    RustLib.instance.api.crateApiBookingsAddCarRental(command: command);

Future<void> updateCarRental({required UpdateCarRental command}) =>
    RustLib.instance.api.crateApiBookingsUpdateCarRental(command: command);

Future<void> deleteCarRental({required UuidValue carRentalId}) =>
    RustLib.instance.api
        .crateApiBookingsDeleteCarRental(carRentalId: carRentalId);

Future<List<Booking>> getTripBookings({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiBookingsGetTripBookings(tripId: tripId);
