// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'events.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `bus`, `emit`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Stream<DataChangeEvent> subscribeDataChanges() =>
    RustLib.instance.api.crateApiEventsSubscribeDataChanges();

@freezed
sealed class DataChangeEvent with _$DataChangeEvent {
  const DataChangeEvent._();

  const factory DataChangeEvent.tripsChanged() = DataChangeEvent_TripsChanged;
  const factory DataChangeEvent.tripChanged({
    required UuidValue tripId,
  }) = DataChangeEvent_TripChanged;
  const factory DataChangeEvent.locationsChanged({
    required UuidValue tripId,
  }) = DataChangeEvent_LocationsChanged;
  const factory DataChangeEvent.weatherUpdated({
    required UuidValue tripId,
    required UuidValue locationId,
  }) = DataChangeEvent_WeatherUpdated;
  const factory DataChangeEvent.pollenUpdated({
    required UuidValue tripId,
    required UuidValue locationId,
  }) = DataChangeEvent_PollenUpdated;
  const factory DataChangeEvent.tidesUpdated({
    required UuidValue tripId,
    required UuidValue locationId,
  }) = DataChangeEvent_TidesUpdated;
  const factory DataChangeEvent.packingListChanged({
    UuidValue? tripId,
  }) = DataChangeEvent_PackingListChanged;
  const factory DataChangeEvent.accommodationsChanged({
    UuidValue? tripId,
  }) = DataChangeEvent_AccommodationsChanged;
  const factory DataChangeEvent.bookingsChanged({
    UuidValue? tripId,
  }) = DataChangeEvent_BookingsChanged;
  const factory DataChangeEvent.transitsChanged({
    UuidValue? tripId,
  }) = DataChangeEvent_TransitsChanged;
  const factory DataChangeEvent.poisChanged({
    UuidValue? tripId,
  }) = DataChangeEvent_PoisChanged;
  const factory DataChangeEvent.routesChanged({
    UuidValue? tripId,
  }) = DataChangeEvent_RoutesChanged;
  const factory DataChangeEvent.attachmentsChanged({
    UuidValue? tripId,
    UuidValue? accommodationId,
  }) = DataChangeEvent_AttachmentsChanged;
  const factory DataChangeEvent.tagsChanged() = DataChangeEvent_TagsChanged;
  const factory DataChangeEvent.tripDaysChanged({
    required UuidValue tripId,
  }) = DataChangeEvent_TripDaysChanged;
}
