// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../commands/add_packing_list_entry.dart';
import '../commands/delete_packing_list_entry.dart';
import '../commands/update_packing_list_entry.dart';
import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<List<PackingListEntry>> getPackingList() =>
    RustLib.instance.api.crateApiPackingListGetPackingList();

Future<void> addPackingListEntry({required AddPackingListEntry command}) =>
    RustLib.instance.api
        .crateApiPackingListAddPackingListEntry(command: command);

Future<void> updatePackingListEntry(
        {required UpdatePackingListEntry command}) =>
    RustLib.instance.api
        .crateApiPackingListUpdatePackingListEntry(command: command);

Future<void> deletePackingListEntry(
        {required DeletePackingListEntry command}) =>
    RustLib.instance.api
        .crateApiPackingListDeletePackingListEntry(command: command);
