// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../commands/add_trip_point_of_interest.dart';
import '../commands/update_trip_point_of_interest.dart';
import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<List<PointOfInterestModel>> getTripPointsOfInterest(
        {required UuidValue tripId}) =>
    RustLib.instance.api
        .crateApiPointsOfInterestGetTripPointsOfInterest(tripId: tripId);

Future<void> addTripPointOfInterest(
        {required AddTripPointOfInterest command}) =>
    RustLib.instance.api
        .crateApiPointsOfInterestAddTripPointOfInterest(command: command);

Future<void> updateTripPointOfInterest(
        {required UpdateTripPointOfInterest command}) =>
    RustLib.instance.api
        .crateApiPointsOfInterestUpdateTripPointOfInterest(command: command);

Future<void> deletePointOfInterest({required UuidValue pointOfInterestId}) =>
    RustLib.instance.api.crateApiPointsOfInterestDeletePointOfInterest(
        pointOfInterestId: pointOfInterestId);
