// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../commands/import_komoot_route.dart';
import '../commands/update_route.dart';
import '../frb_generated.dart';
import '../models.dart';
import '../models/routes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<RouteModel> importKomootRoute({required ImportKomootRoute command}) =>
    RustLib.instance.api.crateApiRoutesImportKomootRoute(command: command);

Future<List<RouteModel>> getTripRoutes({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiRoutesGetTripRoutes(tripId: tripId);

Future<void> updateRoute({required UpdateRoute command}) =>
    RustLib.instance.api.crateApiRoutesUpdateRoute(command: command);

Future<void> deleteRoute({required UuidValue routeId}) =>
    RustLib.instance.api.crateApiRoutesDeleteRoute(routeId: routeId);
