// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<TripMemberModel>> listTripMembers({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiSharingListTripMembers(tripId: tripId);

Future<void> inviteTripMember(
        {required UuidValue tripId, required String email}) =>
    RustLib.instance.api
        .crateApiSharingInviteTripMember(tripId: tripId, email: email);

Future<void> removeTripMember(
        {required UuidValue tripId, required UuidValue userId}) =>
    RustLib.instance.api
        .crateApiSharingRemoveTripMember(tripId: tripId, userId: userId);

Future<void> leaveTrip({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiSharingLeaveTrip(tripId: tripId);

Future<List<PendingInviteModel>> listOutboundInvites(
        {required UuidValue tripId}) =>
    RustLib.instance.api.crateApiSharingListOutboundInvites(tripId: tripId);

Future<void> revokeInvite(
        {required UuidValue tripId, required UuidValue inviteId}) =>
    RustLib.instance.api
        .crateApiSharingRevokeInvite(tripId: tripId, inviteId: inviteId);

class PendingInviteModel {
  final UuidValue id;
  final String email;
  final DateTime createdAt;

  const PendingInviteModel({
    required this.id,
    required this.email,
    required this.createdAt,
  });

  @override
  int get hashCode => id.hashCode ^ email.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingInviteModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email &&
          createdAt == other.createdAt;
}

class TripMemberModel {
  final UuidValue userId;
  final String? email;
  final String? displayName;
  final bool isOwner;
  final bool isSelf;

  const TripMemberModel({
    required this.userId,
    this.email,
    this.displayName,
    required this.isOwner,
    required this.isSelf,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      email.hashCode ^
      displayName.hashCode ^
      isOwner.hashCode ^
      isSelf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripMemberModel &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          email == other.email &&
          displayName == other.displayName &&
          isOwner == other.isOwner &&
          isSelf == other.isSelf;
}
