// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'sync.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Configure the Supabase client. Called once at app startup with the
/// project URL and anon key (typically passed via `--dart-define`).
Future<void> configureSync({required String url, required String anonKey}) =>
    RustLib.instance.api.crateApiSyncConfigureSync(url: url, anonKey: anonKey);

/// Push the current auth session into Rust. Dart calls this on every
/// `onAuthStateChange` after `supabase_flutter` signs in / refreshes the
/// JWT. Pass `None` to sign out.
Future<void> setAuthSession({AuthSession? session}) =>
    RustLib.instance.api.crateApiSyncSetAuthSession(session: session);

/// How many local trips were created while anonymous and haven't been
/// pushed yet. Drives the "Upload N trips" button on the sync sheet.
Future<BigInt> localOnlyTripCount() =>
    RustLib.instance.api.crateApiSyncLocalOnlyTripCount();

/// Claim every anonymous trip for the signed-in user and enqueue its
/// full subtree for push. Returns the number of trips queued.
Future<BigInt> uploadLocalOnlyTrips() =>
    RustLib.instance.api.crateApiSyncUploadLocalOnlyTrips();

/// Claim a single trip for the signed-in user and enqueue its subtree.
/// Used by the per-card "sync this trip" button on the trip list.
Future<void> uploadTrip({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiSyncUploadTrip(tripId: tripId);

/// Read the current user's profile row from local SQLite. Returns
/// `None` if the user is signed out OR if the profile pull hasn't
/// brought their row down yet (rare race on first sign-in).
Future<MyProfile?> getMyProfile() =>
    RustLib.instance.api.crateApiSyncGetMyProfile();

/// Update the user's display name. The trimmed value is pushed straight
/// to PostgREST (RLS scopes writes to the caller's own row) and then
/// applied locally so the UI doesn't have to wait for a pull. An
/// empty / whitespace-only string clears the name.
Future<void> updateMyProfile({String? displayName}) =>
    RustLib.instance.api.crateApiSyncUpdateMyProfile(displayName: displayName);

/// Delete the signed-in user's account: wipe the server-side data
/// (via the `delete_my_account` RPC) and unlink every local trip so
/// they live on as anonymous local-only data.
Future<void> deleteAccount() =>
    RustLib.instance.api.crateApiSyncDeleteAccount();

/// Stream of [`SyncStatus`] updates for the UI. Mirrors the pattern used
/// by `subscribe_data_changes`.
Stream<SyncStatus> syncStatusStream() =>
    RustLib.instance.api.crateApiSyncSyncStatusStream();

class AuthSession {
  final String accessToken;
  final String refreshToken;
  final String userId;
  final PlatformInt64 expiresAtUnixSeconds;

  const AuthSession({
    required this.accessToken,
    required this.refreshToken,
    required this.userId,
    required this.expiresAtUnixSeconds,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^
      refreshToken.hashCode ^
      userId.hashCode ^
      expiresAtUnixSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthSession &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          userId == other.userId &&
          expiresAtUnixSeconds == other.expiresAtUnixSeconds;
}

/// Snapshot of the signed-in user's profile row used by the account
/// screen. Returned by [`get_my_profile`].
class MyProfile {
  final UuidValue userId;
  final String email;
  final String? displayName;

  const MyProfile({
    required this.userId,
    required this.email,
    this.displayName,
  });

  @override
  int get hashCode => userId.hashCode ^ email.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MyProfile &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          email == other.email &&
          displayName == other.displayName;
}

@freezed
sealed class SyncStatus with _$SyncStatus {
  const SyncStatus._();

  /// No user is signed in; sync is dormant.
  const factory SyncStatus.signedOut() = SyncStatus_SignedOut;

  /// Signed in, sync is configured but no transport is active yet.
  const factory SyncStatus.idle() = SyncStatus_Idle;

  /// Bringing the realtime channel up.
  const factory SyncStatus.connecting() = SyncStatus_Connecting;

  /// Realtime is live; changes flow both directions.
  const factory SyncStatus.live() = SyncStatus_Live;

  /// A push/pull batch is in flight.
  const factory SyncStatus.syncing() = SyncStatus_Syncing;

  /// We lost network or the WS dropped; the worker will reconnect.
  const factory SyncStatus.offline() = SyncStatus_Offline;

  /// Non-recoverable error surface for the UI; the message is human-readable.
  const factory SyncStatus.error({
    required String message,
  }) = SyncStatus_Error;
}
