// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../commands/add_train.dart';
import '../commands/parse_shared_train_data.dart';
import '../commands/parse_train_data.dart';
import '../commands/update_train.dart';
import '../frb_generated.dart';
import '../models/transits.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<void> addTrain({required AddTrain command}) =>
    RustLib.instance.api.crateApiTransitsAddTrain(command: command);

Future<void> updateTrain({required UpdateTrain command}) =>
    RustLib.instance.api.crateApiTransitsUpdateTrain(command: command);

Future<void> deleteTrain({required UuidValue trainId}) =>
    RustLib.instance.api.crateApiTransitsDeleteTrain(trainId: trainId);

Future<List<Train>> getTripTrains({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiTransitsGetTripTrains(tripId: tripId);

Future<void> importParsedTrainJourney(
        {required ImportParsedTrainJourney command}) =>
    RustLib.instance.api
        .crateApiTransitsImportParsedTrainJourney(command: command);

Future<ParsedTrainJourney> parseTrainData({required ParseTrainData command}) =>
    RustLib.instance.api.crateApiTransitsParseTrainData(command: command);
