// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../commands/add_trip_location.dart';
import '../commands/create_trip.dart';
import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<List<TripListModel>> getTrips() =>
    RustLib.instance.api.crateApiTripsGetTrips();

Future<List<TripListModel>> getUpcomingTrips() =>
    RustLib.instance.api.crateApiTripsGetUpcomingTrips();

Future<List<TripListModel>> getPastTrips() =>
    RustLib.instance.api.crateApiTripsGetPastTrips();

Future<TripOverviewModel> getTrip({required UuidValue id}) =>
    RustLib.instance.api.crateApiTripsGetTrip(id: id);

Future<TripOverviewModel> createTrip({required CreateTrip command}) =>
    RustLib.instance.api.crateApiTripsCreateTrip(command: command);

Future<TripPackingListModel> getTripPackingList({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiTripsGetTripPackingList(tripId: tripId);

Future<void> markAsPacked(
        {required UuidValue tripId, required UuidValue entryId}) =>
    RustLib.instance.api
        .crateApiTripsMarkAsPacked(tripId: tripId, entryId: entryId);

Future<void> markAsUnpacked(
        {required UuidValue tripId, required UuidValue entryId}) =>
    RustLib.instance.api
        .crateApiTripsMarkAsUnpacked(tripId: tripId, entryId: entryId);

Future<List<LocationEntry>> searchLocations({required String query}) =>
    RustLib.instance.api.crateApiTripsSearchLocations(query: query);

Future<void> addTripLocation({required AddTripLocation command}) =>
    RustLib.instance.api.crateApiTripsAddTripLocation(command: command);

Future<List<TripLocationListModel>> getTripLocations(
        {required UuidValue tripId}) =>
    RustLib.instance.api.crateApiTripsGetTripLocations(tripId: tripId);
