// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../commands/trip_day.dart';
import '../frb_generated.dart';
import '../models.dart';
import '../models/bookings.dart';
import '../models/trip_day.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<List<TripDayView>> getTripDays({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiTripDaysGetTripDays(tripId: tripId);

Future<UnassignedItems> getUnassignedDayItems({required UuidValue tripId}) =>
    RustLib.instance.api.crateApiTripDaysGetUnassignedDayItems(tripId: tripId);

Future<void> assignItemToDay({required AssignItemToDay command}) =>
    RustLib.instance.api.crateApiTripDaysAssignItemToDay(command: command);

Future<void> unassignDayItem(
        {required UuidValue tripId, required UnassignItem command}) =>
    RustLib.instance.api
        .crateApiTripDaysUnassignDayItem(tripId: tripId, command: command);

Future<void> reorderTripDay(
        {required UuidValue tripId, required ReorderDay command}) =>
    RustLib.instance.api
        .crateApiTripDaysReorderTripDay(tripId: tripId, command: command);

Future<void> setTripDayTitle({required SetTripDayTitle command}) =>
    RustLib.instance.api.crateApiTripDaysSetTripDayTitle(command: command);

Future<void> addTripDayLocation({required AddTripDayLocation command}) =>
    RustLib.instance.api.crateApiTripDaysAddTripDayLocation(command: command);

Future<void> removeTripDayLocation(
        {required UuidValue tripId, required RemoveTripDayLocation command}) =>
    RustLib.instance.api.crateApiTripDaysRemoveTripDayLocation(
        tripId: tripId, command: command);

Future<void> setPrimaryTripDayLocation(
        {required UuidValue tripId,
        required SetPrimaryTripDayLocation command}) =>
    RustLib.instance.api.crateApiTripDaysSetPrimaryTripDayLocation(
        tripId: tripId, command: command);
